//#ifdef _WIN32_WCE

/* This file has been automatically generated by the genstroke utility. */

#include "glutes_internal.h"

/* char: 0x20 */

static const SFG_StrokeStrip ch32st[] =
{
  { 0, NULL }
};

static const SFG_StrokeChar ch32 = {6865676,0,ch32st};

/* char: 0x21 */

static const SFG_StrokeVertex ch33st0[] =
{
 {876996,6553600},
 {876996,2184531}
};

static const SFG_StrokeVertex ch33st1[] =
{
 {876996,624151},
 {564920,312075},
 {876996,0},
 {1189072,312075},
 {876996,624151}
};

static const SFG_StrokeStrip ch33st[] =
{
 {2,ch33st0},
 {5,ch33st1}
};

static const SFG_StrokeChar ch33 = {1744817,2,ch33st};

/* char: 0x22 */

static const SFG_StrokeVertex ch34st0[] =
{
 {263454,6553600},
 {263454,4369069}
};

static const SFG_StrokeVertex ch34st1[] =
{
 {2760061,6553600},
 {2760061,4369069}
};

static const SFG_StrokeStrip ch34st[] =
{
 {2,ch34st0},
 {2,ch34st1}
};

static const SFG_StrokeChar ch34 = {3370857,2,ch34st};

/* char: 0x23 */

static const SFG_StrokeVertex ch35st0[] =
{
 {2706322,7801903},
 {521791,-2184531}
};

static const SFG_StrokeVertex ch35st1[] =
{
 {4578784,7801903},
 {2394246,-2184531}
};

static const SFG_StrokeVertex ch35st2[] =
{
 {521791,3744917},
 {4890859,3744917}
};

static const SFG_StrokeVertex ch35st3[] =
{
 {209715,1872455},
 {4578784,1872455}
};

static const SFG_StrokeStrip ch35st[] =
{
 {2,ch35st0},
 {2,ch35st1},
 {2,ch35st2},
 {2,ch35st3}
};

static const SFG_StrokeChar ch35 = {5209364,4,ch35st};

/* char: 0x24 */

static const SFG_StrokeVertex ch36st0[] =
{
 {1876262,7801903},
 {1876262,-1248303}
};

static const SFG_StrokeVertex ch36st1[] =
{
 {3124566,7801903},
 {3124566,-1248303}
};

static const SFG_StrokeVertex ch36st2[] =
{
 {4684952,5617372},
 {4060800,6241524},
 {3124566,6553600},
 {1876262,6553600},
 {940035,6241524},
 {315883,5617372},
 {315883,4993220},
 {627959,4369069},
 {940035,4056993},
 {1564187,3744917},
 {3436642,3120758},
 {4060800,2808683},
 {4372876,2496607},
 {4684952,1872455},
 {4684952,936227},
 {4060800,312075},
 {3124566,0},
 {1876262,0},
 {940035,312075},
 {315883,936227}
};

static const SFG_StrokeStrip ch36st[] =
{
 {2,ch36st0},
 {2,ch36st1},
 {20,ch36st2}
};

static const SFG_StrokeChar ch36 = {4994282,3,ch36st};

/* char: 0x25 */

static const SFG_StrokeVertex ch37st0[] =
{
 {6034181,6553600},
 {416808,0}
};

static const SFG_StrokeVertex ch37st1[] =
{
 {1977188,6553600},
 {2601340,5929448},
 {2601340,5305296},
 {2289264,4681144},
 {1665112,4369069},
 {1040960,4369069},
 {416808,4993220},
 {416808,5617372},
 {728884,6241524},
 {1353036,6553600},
 {1977188,6553600},
 {2601340,6241524},
 {3537567,5929448},
 {4473802,5929448},
 {5410029,6241524},
 {6034181,6553600}
};

static const SFG_StrokeVertex ch37st2[] =
{
 {4785878,2184531},
 {4161726,1872455},
 {3849650,1248303},
 {3849650,624151},
 {4473802,0},
 {5097953,0},
 {5722105,312075},
 {6034181,936227},
 {6034181,1560379},
 {5410029,2184531},
 {4785878,2184531}
};

static const SFG_StrokeStrip ch37st[] =
{
 {2,ch37st0},
 {16,ch37st1},
 {11,ch37st2}
};

static const SFG_StrokeChar ch37 = {6329093,3,ch37st};

/* char: 0x26 */

static const SFG_StrokeVertex ch38st0[] =
{
 {6633429,3744917},
 {6633429,4056993},
 {6321353,4369069},
 {6009278,4369069},
 {5697202,4056993},
 {5385126,3432841},
 {4760974,1872455},
 {4136822,936227},
 {3512664,312075},
 {2888512,0},
 {1640208,0},
 {1016057,312075},
 {703981,624151},
 {391905,1248303},
 {391905,1872455},
 {703981,2496607},
 {1016057,2808683},
 {3200588,4056993},
 {3512664,4369069},
 {3824746,4993220},
 {3824746,5617372},
 {3512664,6241524},
 {2888512,6553600},
 {2264360,6241524},
 {1952284,5617372},
 {1952284,4993220},
 {2264360,4056993},
 {2888512,3120758},
 {4448898,936227},
 {5073050,312075},
 {5697202,0},
 {6321353,0},
 {6633429,312075},
 {6633429,624151}
};

static const SFG_StrokeStrip ch38st[] =
{
 {34,ch38st0}
};

static const SFG_StrokeChar ch38 = {6668818,1,ch38st};

/* char: 0x27 */

static const SFG_StrokeVertex ch39st0[] =
{
 {290979,6553600},
 {290979,4369069}
};

static const SFG_StrokeStrip ch39st[] =
{
 {2,ch39st0}
};

static const SFG_StrokeChar ch39 = {892600,1,ch39st};

/* char: 0x28 */

static const SFG_StrokeVertex ch40st0[] =
{
 {2681294,7801903},
 {2057142,7177752},
 {1432990,6241524},
 {808838,4993220},
 {496762,3432841},
 {496762,2184531},
 {808838,624151},
 {1432990,-624151},
 {2057142,-1560379},
 {2681294,-2184531}
};

static const SFG_StrokeStrip ch40st[] =
{
 {10,ch40st0}
};

static const SFG_StrokeChar ch40 = {3091549,1,ch40st};

/* char: 0x29 */

static const SFG_StrokeVertex ch41st0[] =
{
 {346030,7801903},
 {970181,7177752},
 {1594333,6241524},
 {2218485,4993220},
 {2530561,3432841},
 {2530561,2184531},
 {2218485,624151},
 {1594333,-624151},
 {970181,-1560379},
 {346030,-2184531}
};

static const SFG_StrokeStrip ch41st[] =
{
 {10,ch41st0}
};

static const SFG_StrokeChar ch41 = {3115142,1,ch41st};

/* char: 0x2a */

static const SFG_StrokeVertex ch42st0[] =
{
 {2016510,4681144},
 {2016510,936227}
};

static const SFG_StrokeVertex ch42st1[] =
{
 {456130,3744917},
 {3576889,1872455}
};

static const SFG_StrokeVertex ch42st2[] =
{
 {3576889,3744917},
 {456130,1872455}
};

static const SFG_StrokeStrip ch42st[] =
{
 {2,ch42st0},
 {2,ch42st1},
 {2,ch42st2}
};

static const SFG_StrokeChar ch42 = {3895394,3,ch42st};

/* char: 0x2b */

static const SFG_StrokeVertex ch43st0[] =
{
 {3200588,5617372},
 {3200588,0}
};

static const SFG_StrokeVertex ch43st1[] =
{
 {391905,2808683},
 {6009278,2808683}
};

static const SFG_StrokeStrip ch43st[] =
{
 {2,ch43st0},
 {2,ch43st1}
};

static const SFG_StrokeChar ch43 = {6373658,2,ch43st};

/* char: 0x2c */

static const SFG_StrokeVertex ch44st0[] =
{
 {1198247,312075},
 {886171,0},
 {574095,312075},
 {886171,624151},
 {1198247,312075},
 {1198247,-312075},
 {886171,-936227},
 {574095,-1248303}
};

static const SFG_StrokeStrip ch44st[] =
{
 {8,ch44st0}
};

static const SFG_StrokeChar ch44 = {1708117,1,ch44st};

/* char: 0x2d */

static const SFG_StrokeVertex ch45st0[] =
{
 {483655,2808683},
 {6101028,2808683}
};

static const SFG_StrokeStrip ch45st[] =
{
 {2,ch45st0}
};

static const SFG_StrokeChar ch45 = {6603034,1,ch45st};

/* char: 0x2e */

static const SFG_StrokeVertex ch46st0[] =
{
 {858646,624151},
 {546570,312075},
 {858646,0},
 {1170722,312075},
 {858646,624151}
};

static const SFG_StrokeStrip ch46st[] =
{
 {5,ch46st0}
};

static const SFG_StrokeChar ch46 = {1735642,1,ch46st};

/* char: 0x2f */

static const SFG_StrokeVertex ch47st0[] =
{
 {474480,-936227},
 {4843549,6553600}
};

static const SFG_StrokeStrip ch47st[] =
{
 {2,ch47st0}
};

static const SFG_StrokeChar ch47 = {5380945,1,ch47st};

/* char: 0x30 */

static const SFG_StrokeVertex ch48st0[] =
{
 {2198824,6553600},
 {1262596,6241524},
 {638445,5305296},
 {326369,3744917},
 {326369,2808683},
 {638445,1248303},
 {1262596,312075},
 {2198824,0},
 {2822976,0},
 {3759210,312075},
 {4383362,1248303},
 {4695438,2808683},
 {4695438,3744917},
 {4383362,5305296},
 {3759210,6241524},
 {2822976,6553600},
 {2198824,6553600}
};

static const SFG_StrokeStrip ch48st[] =
{
 {17,ch48st0}
};

static const SFG_StrokeChar ch48 = {5050643,1,ch48st};

/* char: 0x31 */

static const SFG_StrokeVertex ch49st0[] =
{
 {774635,5305296},
 {1398787,5617372},
 {2335015,6553600},
 {2335015,0}
};

static const SFG_StrokeStrip ch49st[] =
{
 {4,ch49st0}
};

static const SFG_StrokeChar ch49 = {4360077,1,ch49st};

/* char: 0x32 */

static const SFG_StrokeVertex ch50st0[] =
{
 {667281,4993220},
 {667281,5305296},
 {979356,5929448},
 {1291432,6241524},
 {1915584,6553600},
 {3163888,6553600},
 {3788046,6241524},
 {4100122,5929448},
 {4412198,5305296},
 {4412198,4681144},
 {4100122,4056993},
 {3475964,3120758},
 {355205,0},
 {4724274,0}
};

static const SFG_StrokeStrip ch50st[] =
{
 {14,ch50st0}
};

static const SFG_StrokeChar ch50 = {5088654,1,ch50st};

/* char: 0x33 */

static const SFG_StrokeVertex ch51st0[] =
{
 {951831,6553600},
 {4384673,6553600},
 {2512211,4056993},
 {3448438,4056993},
 {4072597,3744917},
 {4384673,3432841},
 {4696749,2496607},
 {4696749,1872455},
 {4384673,936227},
 {3760521,312075},
 {2824287,0},
 {1888059,0},
 {951831,312075},
 {639755,624151},
 {327680,1248303}
};

static const SFG_StrokeStrip ch51st[] =
{
 {15,ch51st0}
};

static const SFG_StrokeChar ch51 = {5049332,1,ch51st};

/* char: 0x34 */

static const SFG_StrokeVertex ch52st0[] =
{
 {3375038,6553600},
 {254279,2184531},
 {4935424,2184531}
};

static const SFG_StrokeVertex ch52st1[] =
{
 {3375038,6553600},
 {3375038,0}
};

static const SFG_StrokeStrip ch52st[] =
{
 {3,ch52st0},
 {2,ch52st1}
};

static const SFG_StrokeChar ch52 = {5253929,2,ch52st};

/* char: 0x35 */

static const SFG_StrokeVertex ch53st0[] =
{
 {4063422,6553600},
 {942656,6553600},
 {630580,3744917},
 {942656,4056993},
 {1878884,4369069},
 {2815112,4369069},
 {3751346,4056993},
 {4375498,3432841},
 {4687574,2496607},
 {4687574,1872455},
 {4375498,936227},
 {3751346,312075},
 {2815112,0},
 {1878884,0},
 {942656,312075},
 {630580,624151},
 {318504,1248303}
};

static const SFG_StrokeStrip ch53st[] =
{
 {17,ch53st0}
};

static const SFG_StrokeChar ch53 = {5091275,1,ch53st};

/* char: 0x36 */

static const SFG_StrokeVertex ch54st0[] =
{
 {4110608,5617372},
 {3798532,6241524},
 {2862298,6553600},
 {2238146,6553600},
 {1301918,6241524},
 {677766,5305296},
 {365690,3744917},
 {365690,2184531},
 {677766,936227},
 {1301918,312075},
 {2238146,0},
 {2550222,0},
 {3486449,312075},
 {4110608,936227},
 {4422684,1872455},
 {4422684,2184531},
 {4110608,3120758},
 {3486449,3744917},
 {2550222,4056993},
 {2238146,4056993},
 {1301918,3744917},
 {677766,3120758},
 {365690,2184531}
};

static const SFG_StrokeStrip ch54st[] =
{
 {23,ch54st0}
};

static const SFG_StrokeChar ch54 = {4836871,1,ch54st};

/* char: 0x37 */

static const SFG_StrokeVertex ch55st0[] =
{
 {4733449,6553600},
 {1612683,0}
};

static const SFG_StrokeVertex ch55st1[] =
{
 {364380,6553600},
 {4733449,6553600}
};

static const SFG_StrokeStrip ch55st[] =
{
 {2,ch55st0},
 {2,ch55st1}
};

static const SFG_StrokeChar ch55 = {5061129,2,ch55st};

/* char: 0x38 */

static const SFG_StrokeVertex ch56st0[] =
{
 {1927381,6553600},
 {991153,6241524},
 {679077,5617372},
 {679077,4993220},
 {991153,4369069},
 {1615305,4056993},
 {2863608,3744917},
 {3799842,3432841},
 {4423994,2808683},
 {4736070,2184531},
 {4736070,1248303},
 {4423994,624151},
 {4111918,312075},
 {3175684,0},
 {1927381,0},
 {991153,312075},
 {679077,624151},
 {367001,1248303},
 {367001,2184531},
 {679077,2808683},
 {1303229,3432841},
 {2239456,3744917},
 {3487760,4056993},
 {4111918,4369069},
 {4423994,4993220},
 {4423994,5617372},
 {4111918,6241524},
 {3175684,6553600},
 {1927381,6553600}
};

static const SFG_StrokeStrip ch56st[] =
{
 {29,ch56st0}
};

static const SFG_StrokeChar ch56 = {5089965,1,ch56st};

/* char: 0x39 */

static const SFG_StrokeVertex ch57st0[] =
{
 {4489530,4369069},
 {4177454,3432841},
 {3553296,2808683},
 {2617068,2496607},
 {2304992,2496607},
 {1368765,2808683},
 {744613,3432841},
 {432537,4369069},
 {432537,4681144},
 {744613,5617372},
 {1368765,6241524},
 {2304992,6553600},
 {2617068,6553600},
 {3553296,6241524},
 {4177454,5617372},
 {4489530,4369069},
 {4489530,2808683},
 {4177454,1248303},
 {3553296,312075},
 {2617068,0},
 {1992917,0},
 {1056689,312075},
 {744613,936227}
};

static const SFG_StrokeStrip ch57st[] =
{
 {23,ch57st0}
};

static const SFG_StrokeChar ch57 = {4853911,1,ch57st};

/* char: 0x3a */

static const SFG_StrokeVertex ch58st0[] =
{
 {922871,4369069},
 {610795,4056993},
 {922871,3744917},
 {1234947,4056993},
 {922871,4369069}
};

static const SFG_StrokeVertex ch58st1[] =
{
 {922871,624151},
 {610795,312075},
 {922871,0},
 {1234947,312075},
 {922871,624151}
};

static const SFG_StrokeStrip ch58st[] =
{
 {5,ch58st0},
 {5,ch58st1}
};

static const SFG_StrokeChar ch58 = {1718603,2,ch58st};

/* char: 0x3b */

static const SFG_StrokeVertex ch59st0[] =
{
 {849471,4369069},
 {537395,4056993},
 {849471,3744917},
 {1161547,4056993},
 {849471,4369069}
};

static const SFG_StrokeVertex ch59st1[] =
{
 {1161547,312075},
 {849471,0},
 {537395,312075},
 {849471,624151},
 {1161547,312075},
 {1161547,-312075},
 {849471,-936227},
 {537395,-1248303}
};

static const SFG_StrokeStrip ch59st[] =
{
 {5,ch59st0},
 {8,ch59st1}
};

static const SFG_StrokeChar ch59 = {1723845,2,ch59st};

/* char: 0x3c */

static const SFG_StrokeVertex ch60st0[] =
{
 {5193760,5617372},
 {200540,2808683},
 {5193760,0}
};

static const SFG_StrokeStrip ch60st[] =
{
 {3,ch60st0}
};

static const SFG_StrokeChar ch60 = {5348425,1,ch60st};

/* char: 0x3d */

static const SFG_StrokeVertex ch61st0[] =
{
 {373555,3744917},
 {5990927,3744917}
};

static const SFG_StrokeVertex ch61st1[] =
{
 {373555,1872455},
 {5990927,1872455}
};

static const SFG_StrokeStrip ch61st[] =
{
 {2,ch61st0},
 {2,ch61st1}
};

static const SFG_StrokeChar ch61 = {6373658,2,ch61st};

/* char: 0x3e */

static const SFG_StrokeVertex ch62st0[] =
{
 {182190,5617372},
 {5175410,2808683},
 {182190,0}
};

static const SFG_StrokeStrip ch62st[] =
{
 {3,ch62st0}
};

static const SFG_StrokeChar ch62 = {5348425,1,ch62st};

/* char: 0x3f */

static const SFG_StrokeVertex ch63st0[] =
{
 {551813,4993220},
 {551813,5305296},
 {863889,5929448},
 {1175964,6241524},
 {1800116,6553600},
 {3048420,6553600},
 {3672572,6241524},
 {3984654,5929448},
 {4296730,5305296},
 {4296730,4681144},
 {3984654,4056993},
 {3672572,3744917},
 {2424268,3120758},
 {2424268,2184531}
};

static const SFG_StrokeVertex ch63st1[] =
{
 {2424268,624151},
 {2112192,312075},
 {2424268,0},
 {2736344,312075},
 {2424268,624151}
};

static const SFG_StrokeStrip ch63st[] =
{
 {14,ch63st0},
 {5,ch63st1}
};

static const SFG_StrokeChar ch63 = {4843300,2,ch63st};

/* char: 0x40 */

static const SFG_StrokeVertex ch64st0[] =
{
 {3225492,3432841},
 {2601340,3744917},
 {1977188,3744917},
 {1665112,3120758},
 {1665112,2808683},
 {1977188,2184531},
 {2601340,2184531},
 {3225492,2496607}
};

static const SFG_StrokeVertex ch64st1[] =
{
 {3225492,3744917},
 {3225492,2496607},
 {3537567,2184531},
 {4161726,2184531},
 {4473802,2808683},
 {4473802,3120758},
 {4161726,4056993},
 {3537567,4681144},
 {2601340,4993220},
 {2289264,4993220},
 {1353036,4681144},
 {728884,4056993},
 {416808,3120758},
 {416808,2808683},
 {728884,1872455},
 {1353036,1248303},
 {2289264,936227},
 {2601340,936227},
 {3537567,1248303}
};

static const SFG_StrokeStrip ch64st[] =
{
 {8,ch64st0},
 {19,ch64st1}
};

static const SFG_StrokeChar ch64 = {4873571,2,ch64st};

/* char: 0x41 */

static const SFG_StrokeVertex ch65st0[] =
{
 {2660447,6553600},
 {163840,0}
};

static const SFG_StrokeVertex ch65st1[] =
{
 {2660447,6553600},
 {5157060,0}
};

static const SFG_StrokeVertex ch65st2[] =
{
 {1100067,2184531},
 {4220833,2184531}
};

static const SFG_StrokeStrip ch65st[] =
{
 {2,ch65st0},
 {2,ch65st1},
 {2,ch65st2}
};

static const SFG_StrokeChar ch65 = {5275025,3,ch65st};

/* char: 0x42 */

static const SFG_StrokeVertex ch66st0[] =
{
 {748421,6553600},
 {748421,0}
};

static const SFG_StrokeVertex ch66st1[] =
{
 {748421,6553600},
 {3557104,6553600},
 {4493338,6241524},
 {4805414,5929448},
 {5117490,5305296},
 {5117490,4681144},
 {4805414,4056993},
 {4493338,3744917},
 {3557104,3432841}
};

static const SFG_StrokeVertex ch66st2[] =
{
 {748421,3432841},
 {3557104,3432841},
 {4493338,3120758},
 {4805414,2808683},
 {5117490,2184531},
 {5117490,1248303},
 {4805414,624151},
 {4493338,312075},
 {3557104,0},
 {748421,0}
};

static const SFG_StrokeStrip ch66st[] =
{
 {2,ch66st0},
 {9,ch66st1},
 {10,ch66st2}
};

static const SFG_StrokeChar ch66 = {5480559,3,ch66st};

/* char: 0x43 */

static const SFG_StrokeVertex ch67st0[] =
{
 {5117614,4993220},
 {4805539,5617372},
 {4181386,6241524},
 {3557228,6553600},
 {2308925,6553600},
 {1684773,6241524},
 {1060621,5617372},
 {748545,4993220},
 {436469,4056993},
 {436469,2496607},
 {748545,1560379},
 {1060621,936227},
 {1684773,312075},
 {2308925,0},
 {3557228,0},
 {4181386,312075},
 {4805539,936227},
 {5117614,1560379}
};

static const SFG_StrokeStrip ch67st[] =
{
 {18,ch67st0}
};

static const SFG_StrokeChar ch67 = {5537044,1,ch67st};

/* char: 0x44 */

static const SFG_StrokeVertex ch68st0[] =
{
 {783810,6553600},
 {783810,0}
};

static const SFG_StrokeVertex ch68st1[] =
{
 {783810,6553600},
 {2968341,6553600},
 {3904569,6241524},
 {4528727,5617372},
 {4840803,4993220},
 {5152879,4056993},
 {5152879,2496607},
 {4840803,1560379},
 {4528727,936227},
 {3904569,312075},
 {2968341,0},
 {783810,0}
};

static const SFG_StrokeStrip ch68st[] =
{
 {2,ch68st0},
 {12,ch68st1}
};

static const SFG_StrokeChar ch68 = {5589349,2,ch68st};

/* char: 0x45 */

static const SFG_StrokeVertex ch69st0[] =
{
 {748421,6553600},
 {748421,0}
};

static const SFG_StrokeVertex ch69st1[] =
{
 {748421,6553600},
 {4805414,6553600}
};

static const SFG_StrokeVertex ch69st2[] =
{
 {748421,3432841},
 {3245028,3432841}
};

static const SFG_StrokeVertex ch69st3[] =
{
 {748421,0},
 {4805414,0}
};

static const SFG_StrokeStrip ch69st[] =
{
 {2,ch69st0},
 {2,ch69st1},
 {2,ch69st2},
 {2,ch69st3}
};

static const SFG_StrokeChar ch69 = {5123919,4,ch69st};

/* char: 0x46 */

static const SFG_StrokeVertex ch70st0[] =
{
 {748421,6553600},
 {748421,0}
};

static const SFG_StrokeVertex ch70st1[] =
{
 {748421,6553600},
 {4805414,6553600}
};

static const SFG_StrokeVertex ch70st2[] =
{
 {748421,3432841},
 {3245028,3432841}
};

static const SFG_StrokeStrip ch70st[] =
{
 {2,ch70st0},
 {2,ch70st1},
 {2,ch70st2}
};

static const SFG_StrokeChar ch70 = {5160619,3,ch70st};

/* char: 0x47 */

static const SFG_StrokeVertex ch71st0[] =
{
 {5143828,4993220},
 {4831753,5617372},
 {4207601,6241524},
 {3583443,6553600},
 {2335139,6553600},
 {1710987,6241524},
 {1086835,5617372},
 {774760,4993220},
 {462684,4056993},
 {462684,2496607},
 {774760,1560379},
 {1086835,936227},
 {1710987,312075},
 {2335139,0},
 {3583443,0},
 {4207601,312075},
 {4831753,936227},
 {5143828,1560379},
 {5143828,2496607}
};

static const SFG_StrokeVertex ch71st1[] =
{
 {3583443,2496607},
 {5143828,2496607}
};

static const SFG_StrokeStrip ch71st[] =
{
 {19,ch71st0},
 {2,ch71st1}
};

static const SFG_StrokeChar ch71 = {5883074,2,ch71st};

/* char: 0x48 */

static const SFG_StrokeVertex ch72st0[] =
{
 {748421,6553600},
 {748421,0}
};

static const SFG_StrokeVertex ch72st1[] =
{
 {5117490,6553600},
 {5117490,0}
};

static const SFG_StrokeVertex ch72st2[] =
{
 {748421,3432841},
 {5117490,3432841}
};

static const SFG_StrokeStrip ch72st[] =
{
 {2,ch72st0},
 {2,ch72st1},
 {2,ch72st2}
};

static const SFG_StrokeChar ch72 = {5838386,3,ch72st};

/* char: 0x49 */

static const SFG_StrokeVertex ch73st0[] =
{
 {711720,6553600},
 {711720,0}
};

static const SFG_StrokeStrip ch73st[] =
{
 {2,ch73st0}
};

static const SFG_StrokeChar ch73 = {1395916,1,ch73st};

/* char: 0x4a */

static const SFG_StrokeVertex ch74st0[] =
{
 {3284598,6553600},
 {3284598,1560379},
 {2972523,624151},
 {2660447,312075},
 {2036295,0},
 {1412143,0},
 {787991,312075},
 {475915,624151},
 {163840,1560379},
 {163840,2184531}
};

static const SFG_StrokeStrip ch74st[] =
{
 {10,ch74st0}
};

static const SFG_StrokeChar ch74 = {3932094,1,ch74st};

/* char: 0x4b */

static const SFG_StrokeVertex ch75st0[] =
{
 {739246,6553600},
 {739246,0}
};

static const SFG_StrokeVertex ch75st1[] =
{
 {5108315,6553600},
 {739246,2184531}
};

static const SFG_StrokeVertex ch75st2[] =
{
 {2299625,3744917},
 {5108315,0}
};

static const SFG_StrokeStrip ch75st[] =
{
 {2,ch75st0},
 {2,ch75st1},
 {2,ch75st2}
};

static const SFG_StrokeChar ch75 = {5198754,3,ch75st};

/* char: 0x4c */

static const SFG_StrokeVertex ch76st0[] =
{
 {765460,6553600},
 {765460,0}
};

static const SFG_StrokeVertex ch76st1[] =
{
 {765460,0},
 {4510377,0}
};

static const SFG_StrokeStrip ch76st[] =
{
 {2,ch76st0},
 {2,ch76st1}
};

static const SFG_StrokeChar ch76 = {4674217,2,ch76st};

/* char: 0x4d */

static const SFG_StrokeVertex ch77st0[] =
{
 {711720,6553600},
 {711720,0}
};

static const SFG_StrokeVertex ch77st1[] =
{
 {711720,6553600},
 {3208328,0}
};

static const SFG_StrokeVertex ch77st2[] =
{
 {5704941,6553600},
 {3208328,0}
};

static const SFG_StrokeVertex ch77st3[] =
{
 {5704941,6553600},
 {5704941,0}
};

static const SFG_StrokeStrip ch77st[] =
{
 {2,ch77st0},
 {2,ch77st1},
 {2,ch77st2},
 {2,ch77st3}
};

static const SFG_StrokeChar ch77 = {6370787,4,ch77st};

/* char: 0x4e */

static const SFG_StrokeVertex ch78st0[] =
{
 {730071,6553600},
 {730071,0}
};

static const SFG_StrokeVertex ch78st1[] =
{
 {730071,6553600},
 {5099140,0}
};

static const SFG_StrokeVertex ch78st2[] =
{
 {5099140,6553600},
 {5099140,0}
};

static const SFG_StrokeStrip ch78st[] =
{
 {2,ch78st0},
 {2,ch78st1},
 {2,ch78st2}
};

static const SFG_StrokeChar ch78 = {5820036,3,ch78st};

/* char: 0x4f */

static const SFG_StrokeVertex ch79st0[] =
{
 {2281400,6553600},
 {1657248,6241524},
 {1033096,5617372},
 {721020,4993220},
 {408944,4056993},
 {408944,2496607},
 {721020,1560379},
 {1033096,936227},
 {1657248,312075},
 {2281400,0},
 {3529703,0},
 {4153861,312075},
 {4778013,936227},
 {5090089,1560379},
 {5402165,2496607},
 {5402165,4056993},
 {5090089,4993220},
 {4778013,5617372},
 {4153861,6241524},
 {3529703,6553600},
 {2281400,6553600}
};

static const SFG_StrokeStrip ch79st[] =
{
 {21,ch79st0}
};

static const SFG_StrokeChar ch79 = {5821595,1,ch79st};

/* char: 0x50 */

static const SFG_StrokeVertex ch80st0[] =
{
 {792985,6553600},
 {792985,0}
};

static const SFG_StrokeVertex ch80st1[] =
{
 {792985,6553600},
 {3601668,6553600},
 {4537902,6241524},
 {4849978,5929448},
 {5162054,5305296},
 {5162054,4369069},
 {4849978,3744917},
 {4537902,3432841},
 {3601668,3120758},
 {792985,3120758}
};

static const SFG_StrokeStrip ch80st[] =
{
 {2,ch80st0},
 {10,ch80st1}
};

static const SFG_StrokeChar ch80 = {5614253,2,ch80st};

/* char: 0x51 */

static const SFG_StrokeVertex ch81st0[] =
{
 {2219796,6553600},
 {1595644,6241524},
 {971492,5617372},
 {659416,4993220},
 {347340,4056993},
 {347340,2496607},
 {659416,1560379},
 {971492,936227},
 {1595644,312075},
 {2219796,0},
 {3468099,0},
 {4092257,312075},
 {4716410,936227},
 {5028485,1560379},
 {5340561,2496607},
 {5340561,4056993},
 {5028485,4993220},
 {4716410,5617372},
 {4092257,6241524},
 {3468099,6553600},
 {2219796,6553600}
};

static const SFG_StrokeVertex ch81st1[] =
{
 {3156023,1248303},
 {5028485,-624151}
};

static const SFG_StrokeStrip ch81st[] =
{
 {21,ch81st0},
 {2,ch81st1}
};

static const SFG_StrokeChar ch81 = {5773099,2,ch81st};

/* char: 0x52 */

static const SFG_StrokeVertex ch82st0[] =
{
 {765460,6553600},
 {765460,0}
};

static const SFG_StrokeVertex ch82st1[] =
{
 {765460,6553600},
 {3574143,6553600},
 {4510377,6241524},
 {4822453,5929448},
 {5134529,5305296},
 {5134529,4681144},
 {4822453,4056993},
 {4510377,3744917},
 {3574143,3432841},
 {765460,3432841}
};

static const SFG_StrokeVertex ch82st2[] =
{
 {2949991,3432841},
 {5134529,0}
};

static const SFG_StrokeStrip ch82st[] =
{
 {2,ch82st0},
 {10,ch82st1},
 {2,ch82st2}
};

static const SFG_StrokeChar ch82 = {5397984,3,ch82st};

/* char: 0x53 */

static const SFG_StrokeVertex ch83st0[] =
{
 {4893357,5617372},
 {4269205,6241524},
 {3332971,6553600},
 {2084667,6553600},
 {1148439,6241524},
 {524288,5617372},
 {524288,4993220},
 {836363,4369069},
 {1148439,4056993},
 {1772591,3744917},
 {3645046,3120758},
 {4269205,2808683},
 {4581281,2496607},
 {4893357,1872455},
 {4893357,936227},
 {4269205,312075},
 {3332971,0},
 {2084667,0},
 {1148439,312075},
 {524288,936227}
};

static const SFG_StrokeStrip ch83st[] =
{
 {20,ch83st0}
};

static const SFG_StrokeChar ch83 = {5297059,1,ch83st};

/* char: 0x54 */

static const SFG_StrokeVertex ch84st0[] =
{
 {2339196,6553600},
 {2339196,0}
};

static const SFG_StrokeVertex ch84st1[] =
{
 {154664,6553600},
 {4523734,6553600}
};

static const SFG_StrokeStrip ch84st[] =
{
 {2,ch84st0},
 {2,ch84st1}
};

static const SFG_StrokeChar ch84 = {4715099,2,ch84st};

/* char: 0x55 */

static const SFG_StrokeVertex ch85st0[] =
{
 {756285,6553600},
 {756285,1872455},
 {1068361,936227},
 {1692513,312075},
 {2628740,0},
 {3252892,0},
 {4189126,312075},
 {4813278,936227},
 {5125354,1872455},
 {5125354,6553600}
};

static const SFG_StrokeStrip ch85st[] =
{
 {10,ch85st0}
};

static const SFG_StrokeChar ch85 = {5864600,1,ch85st};

/* char: 0x56 */

static const SFG_StrokeVertex ch86st0[] =
{
 {154664,6553600},
 {2651272,0}
};

static const SFG_StrokeVertex ch86st1[] =
{
 {5147885,6553600},
 {2651272,0}
};

static const SFG_StrokeStrip ch86st[] =
{
 {2,ch86st0},
 {2,ch86st1}
};

static const SFG_StrokeChar ch86 = {5348425,2,ch86st};

/* char: 0x57 */

static const SFG_StrokeVertex ch87st0[] =
{
 {145489,6553600},
 {1705869,0}
};

static const SFG_StrokeVertex ch87st1[] =
{
 {3266248,6553600},
 {1705869,0}
};

static const SFG_StrokeVertex ch87st2[] =
{
 {3266248,6553600},
 {4826634,0}
};

static const SFG_StrokeVertex ch87st3[] =
{
 {6387014,6553600},
 {4826634,0}
};

static const SFG_StrokeStrip ch87st[] =
{
 {2,ch87st0},
 {2,ch87st1},
 {2,ch87st2},
 {2,ch87st3}
};

static const SFG_StrokeChar ch87 = {6587554,4,ch87st};

/* char: 0x58 */

static const SFG_StrokeVertex ch88st0[] =
{
 {163840,6553600},
 {4532909,0}
};

static const SFG_StrokeVertex ch88st1[] =
{
 {4532909,6553600},
 {163840,0}
};

static const SFG_StrokeStrip ch88st[] =
{
 {2,ch88st0},
 {2,ch88st1}
};

static const SFG_StrokeChar ch88 = {4742624,2,ch88st};

/* char: 0x59 */

static const SFG_StrokeVertex ch89st0[] =
{
 {99614,6553600},
 {2596221,3432841},
 {2596221,0}
};

static const SFG_StrokeVertex ch89st1[] =
{
 {5092835,6553600},
 {2596221,3432841}
};

static const SFG_StrokeStrip ch89st[] =
{
 {3,ch89st0},
 {2,ch89st1}
};

static const SFG_StrokeChar ch89 = {5219975,2,ch89st};

/* char: 0x5a */

static const SFG_StrokeVertex ch90st0[] =
{
 {4532909,6553600},
 {163840,0}
};

static const SFG_StrokeVertex ch90st1[] =
{
 {163840,6553600},
 {4532909,6553600}
};

static const SFG_StrokeVertex ch90st2[] =
{
 {163840,0},
 {4532909,0}
};

static const SFG_StrokeStrip ch90st[] =
{
 {2,ch90st0},
 {2,ch90st1},
 {2,ch90st2}
};

static const SFG_StrokeChar ch90 = {4833064,3,ch90st};

/* char: 0x5b */

static const SFG_StrokeVertex ch91st0[] =
{
 {509870,7801903},
 {509870,-2184531}
};

static const SFG_StrokeVertex ch91st1[] =
{
 {821946,7801903},
 {821946,-2184531}
};

static const SFG_StrokeVertex ch91st2[] =
{
 {509870,7801903},
 {2694401,7801903}
};

static const SFG_StrokeVertex ch91st3[] =
{
 {509870,-2184531},
 {2694401,-2184531}
};

static const SFG_StrokeStrip ch91st[] =
{
 {2,ch91st0},
 {2,ch91st1},
 {2,ch91st2},
 {2,ch91st3}
};

static const SFG_StrokeChar ch91 = {3022081,4,ch91st};

/* char: 0x5c */

static const SFG_StrokeVertex ch92st0[] =
{
 {382730,6553600},
 {4751799,-936227}
};

static const SFG_StrokeStrip ch92st[] =
{
 {2,ch92st0}
};

static const SFG_StrokeChar ch92 = {5125354,1,ch92st};

/* char: 0x5d */

static const SFG_StrokeVertex ch93st0[] =
{
 {2163435,7801903},
 {2163435,-2184531}
};

static const SFG_StrokeVertex ch93st1[] =
{
 {2475511,7801903},
 {2475511,-2184531}
};

static const SFG_StrokeVertex ch93st2[] =
{
 {290979,7801903},
 {2475511,7801903}
};

static const SFG_StrokeVertex ch93st3[] =
{
 {290979,-2184531},
 {2475511,-2184531}
};

static const SFG_StrokeStrip ch93st[] =
{
 {2,ch93st0},
 {2,ch93st1},
 {2,ch93st2},
 {2,ch93st3}
};

static const SFG_StrokeChar ch93 = {3040431,4,ch93st};

/* char: 0x5e */

static const SFG_StrokeVertex ch94st0[] =
{
 {2888512,7177752},
 {391905,2808683}
};

static const SFG_StrokeVertex ch94st1[] =
{
 {2888512,7177752},
 {5385126,2808683}
};

static const SFG_StrokeStrip ch94st[] =
{
 {2,ch94st0},
 {2,ch94st1}
};

static const SFG_StrokeChar ch94 = {5913346,2,ch94st};

/* char: 0x5f */

static const SFG_StrokeVertex ch95st0[] =
{
 {-72089,-2184531},
 {6793586,-2184531},
 {6793586,-1872455},
 {-72089,-1872455},
 {-72089,-2184531}
};

static const SFG_StrokeStrip ch95st[] =
{
 {5,ch95st0}
};

static const SFG_StrokeChar ch95 = {6819801,1,ch95st};

/* char: 0x60 */

static const SFG_StrokeVertex ch96st0[] =
{
 {2164123,6553600},
 {3724502,4681144}
};

static const SFG_StrokeVertex ch96st1[] =
{
 {2164123,6553600},
 {1852047,6241524},
 {3724502,4681144}
};

static const SFG_StrokeStrip ch96st[] =
{
 {2,ch96st0},
 {3,ch96st1}
};

static const SFG_StrokeChar ch96 = {5476935,2,ch96st};

/* char: 0x61 */

static const SFG_StrokeVertex ch97st0[] =
{
 {4182697,4369069},
 {4182697,0}
};

static const SFG_StrokeVertex ch97st1[] =
{
 {4182697,3432841},
 {3558539,4056993},
 {2934387,4369069},
 {1998159,4369069},
 {1374008,4056993},
 {749856,3432841},
 {437780,2496607},
 {437780,1872455},
 {749856,936227},
 {1374008,312075},
 {1998159,0},
 {2934387,0},
 {3558539,312075},
 {4182697,936227}
};

static const SFG_StrokeStrip ch97st[] =
{
 {2,ch97st0},
 {14,ch97st1}
};

static const SFG_StrokeChar ch97 = {4364887,2,ch97st};

/* char: 0x62 */

static const SFG_StrokeVertex ch98st0[] =
{
 {574095,6553600},
 {574095,0}
};

static const SFG_StrokeVertex ch98st1[] =
{
 {574095,3432841},
 {1198247,4056993},
 {1822398,4369069},
 {2758626,4369069},
 {3382778,4056993},
 {4006936,3432841},
 {4319012,2496607},
 {4319012,1872455},
 {4006936,936227},
 {3382778,312075},
 {2758626,0},
 {1822398,0},
 {1198247,312075},
 {574095,936227}
};

static const SFG_StrokeStrip ch98st[] =
{
 {2,ch98st0},
 {14,ch98st1}
};

static const SFG_StrokeChar ch98 = {4617856,2,ch98st};

/* char: 0x63 */

static const SFG_StrokeVertex ch99st0[] =
{
 {4106675,3432841},
 {3482517,4056993},
 {2858365,4369069},
 {1922138,4369069},
 {1297986,4056993},
 {673834,3432841},
 {361758,2496607},
 {361758,1872455},
 {673834,936227},
 {1297986,312075},
 {1922138,0},
 {2858365,0},
 {3482517,312075},
 {4106675,936227}
};

static const SFG_StrokeStrip ch99st[] =
{
 {14,ch99st0}
};

static const SFG_StrokeChar ch99 = {4516931,1,ch99st};

/* char: 0x64 */

static const SFG_StrokeVertex ch100st0[] =
{
 {4049004,6553600},
 {4049004,0}
};

static const SFG_StrokeVertex ch100st1[] =
{
 {4049004,3432841},
 {3424845,4056993},
 {2800694,4369069},
 {1864466,4369069},
 {1240314,4056993},
 {616162,3432841},
 {304087,2496607},
 {304087,1872455},
 {616162,936227},
 {1240314,312075},
 {1864466,0},
 {2800694,0},
 {3424845,312075},
 {4049004,936227}
};

static const SFG_StrokeStrip ch100st[] =
{
 {2,ch100st0},
 {14,ch100st1}
};

static const SFG_StrokeChar ch100 = {4604749,2,ch100st};

/* char: 0x65 */

static const SFG_StrokeVertex ch101st0[] =
{
 {374865,2496607},
 {4119783,2496607},
 {4119783,3120758},
 {3807707,3744917},
 {3495624,4056993},
 {2871473,4369069},
 {1935245,4369069},
 {1311093,4056993},
 {686941,3432841},
 {374865,2496607},
 {374865,1872455},
 {686941,936227},
 {1311093,312075},
 {1935245,0},
 {2871473,0},
 {3495624,312075},
 {4119783,936227}
};

static const SFG_StrokeStrip ch101st[] =
{
 {17,ch101st0}
};

static const SFG_StrokeChar ch101 = {4490716,1,ch101st};

/* char: 0x66 */

static const SFG_StrokeVertex ch102st0[] =
{
 {2541171,6553600},
 {1917019,6553600},
 {1292868,6241524},
 {980792,5305296},
 {980792,0}
};

static const SFG_StrokeVertex ch102st1[] =
{
 {44564,4369069},
 {2229095,4369069}
};

static const SFG_StrokeStrip ch102st[] =
{
 {5,ch102st0},
 {2,ch102st1}
};

static const SFG_StrokeChar ch102 = {2533307,2,ch102st};

/* char: 0x67 */

static const SFG_StrokeVertex ch103st0[] =
{
 {4096190,4369069},
 {4096190,-624151},
 {3784114,-1560379},
 {3472031,-1872455},
 {2847880,-2184531},
 {1911652,-2184531},
 {1287500,-1872455}
};

static const SFG_StrokeVertex ch103st1[] =
{
 {4096190,3432841},
 {3472031,4056993},
 {2847880,4369069},
 {1911652,4369069},
 {1287500,4056993},
 {663348,3432841},
 {351272,2496607},
 {351272,1872455},
 {663348,936227},
 {1287500,312075},
 {1911652,0},
 {2847880,0},
 {3472031,312075},
 {4096190,936227}
};

static const SFG_StrokeStrip ch103st[] =
{
 {7,ch103st0},
 {14,ch103st1}
};

static const SFG_StrokeChar ch103 = {4651935,2,ch103st};

/* char: 0x68 */

static const SFG_StrokeVertex ch104st0[] =
{
 {629145,6553600},
 {629145,0}
};

static const SFG_StrokeVertex ch104st1[] =
{
 {629145,3120758},
 {1565373,4056993},
 {2189525,4369069},
 {3125752,4369069},
 {3749904,4056993},
 {4061987,3120758},
 {4061987,0}
};

static const SFG_StrokeStrip ch104st[] =
{
 {2,ch104st0},
 {7,ch104st1}
};

static const SFG_StrokeChar ch104 = {4654432,2,ch104st};

/* char: 0x69 */

static const SFG_StrokeVertex ch105st0[] =
{
 {656670,6553600},
 {968746,6241524},
 {1280822,6553600},
 {968746,6865676},
 {656670,6553600}
};

static const SFG_StrokeVertex ch105st1[] =
{
 {968746,4369069},
 {968746,0}
};

static const SFG_StrokeStrip ch105st[] =
{
 {5,ch105st0},
 {2,ch105st1}
};

static const SFG_StrokeChar ch105 = {1891618,2,ch105st};

/* char: 0x6a */

static const SFG_StrokeVertex ch106st0[] =
{
 {1139513,6553600},
 {1451589,6241524},
 {1763665,6553600},
 {1451589,6865676},
 {1139513,6553600}
};

static const SFG_StrokeVertex ch106st1[] =
{
 {1451589,4369069},
 {1451589,-936227},
 {1139513,-1872455},
 {515362,-2184531},
 {-108789,-2184531}
};

static const SFG_StrokeStrip ch106st[] =
{
 {5,ch106st0},
 {5,ch106st1}
};

static const SFG_StrokeChar ch106 = {2374461,2,ch106st};

/* char: 0x6b */

static const SFG_StrokeVertex ch107st0[] =
{
 {629145,6553600},
 {629145,0}
};

static const SFG_StrokeVertex ch107st1[] =
{
 {3749904,4369069},
 {629145,1248303}
};

static const SFG_StrokeVertex ch107st2[] =
{
 {1877449,2496607},
 {4061987,0}
};

static const SFG_StrokeStrip ch107st[] =
{
 {2,ch107st0},
 {2,ch107st1},
 {2,ch107st2}
};

static const SFG_StrokeChar ch107 = {4097376,3,ch107st};

/* char: 0x6c */

static const SFG_StrokeVertex ch108st0[] =
{
 {656670,6553600},
 {656670,0}
};

static const SFG_StrokeStrip ch108st[] =
{
 {2,ch108st0}
};

static const SFG_StrokeChar ch108 = {1267466,1,ch108st};

/* char: 0x6d */

static const SFG_StrokeVertex ch109st0[] =
{
 {629145,4369069},
 {629145,0}
};

static const SFG_StrokeVertex ch109st1[] =
{
 {629145,3120758},
 {1565373,4056993},
 {2189525,4369069},
 {3125752,4369069},
 {3749904,4056993},
 {4061987,3120758},
 {4061987,0}
};

static const SFG_StrokeVertex ch109st2[] =
{
 {4061987,3120758},
 {4998214,4056993},
 {5622366,4369069},
 {6558593,4369069},
 {7182745,4056993},
 {7494821,3120758},
 {7494821,0}
};

static const SFG_StrokeStrip ch109st[] =
{
 {2,ch109st0},
 {7,ch109st1},
 {7,ch109st2}
};

static const SFG_StrokeChar ch109 = {8123967,3,ch109st};

/* char: 0x6e */

static const SFG_StrokeVertex ch110st0[] =
{
 {601620,4369069},
 {601620,0}
};

static const SFG_StrokeVertex ch110st1[] =
{
 {601620,3120758},
 {1537848,4056993},
 {2162000,4369069},
 {3098227,4369069},
 {3722379,4056993},
 {4034461,3120758},
 {4034461,0}
};

static const SFG_StrokeStrip ch110st[] =
{
 {2,ch110st0},
 {7,ch110st1}
};

static const SFG_StrokeChar ch110 = {4645257,2,ch110st};

/* char: 0x6f */

static const SFG_StrokeVertex ch111st0[] =
{
 {1886748,4369069},
 {1262596,4056993},
 {638445,3432841},
 {326369,2496607},
 {326369,1872455},
 {638445,936227},
 {1262596,312075},
 {1886748,0},
 {2822976,0},
 {3447128,312075},
 {4071286,936227},
 {4383362,1872455},
 {4383362,2496607},
 {4071286,3432841},
 {3447128,4056993},
 {2822976,4369069},
 {1886748,4369069}
};

static const SFG_StrokeStrip ch111st[] =
{
 {17,ch111st0}
};

static const SFG_StrokeChar ch111 = {4701867,1,ch111st};

/* char: 0x70 */

static const SFG_StrokeVertex ch112st0[] =
{
 {619970,4369069},
 {619970,-2184531}
};

static const SFG_StrokeVertex ch112st1[] =
{
 {619970,3432841},
 {1244122,4056993},
 {1868274,4369069},
 {2804501,4369069},
 {3428653,4056993},
 {4052811,3432841},
 {4364887,2496607},
 {4364887,1872455},
 {4052811,936227},
 {3428653,312075},
 {2804501,0},
 {1868274,0},
 {1244122,312075},
 {619970,936227}
};

static const SFG_StrokeStrip ch112st[] =
{
 {2,ch112st0},
 {14,ch112st1}
};

static const SFG_StrokeChar ch112 = {4640139,2,ch112st};

/* char: 0x71 */

static const SFG_StrokeVertex ch113st0[] =
{
 {4062111,4369069},
 {4062111,-2184531}
};

static const SFG_StrokeVertex ch113st1[] =
{
 {4062111,3432841},
 {3437953,4056993},
 {2813801,4369069},
 {1877573,4369069},
 {1253421,4056993},
 {629270,3432841},
 {317194,2496607},
 {317194,1872455},
 {629270,936227},
 {1253421,312075},
 {1877573,0},
 {2813801,0},
 {3437953,312075},
 {4062111,936227}
};

static const SFG_StrokeStrip ch113st[] =
{
 {2,ch113st0},
 {14,ch113st1}
};

static const SFG_StrokeChar ch113 = {4636206,2,ch113st};

/* char: 0x72 */

static const SFG_StrokeVertex ch114st0[] =
{
 {619970,4369069},
 {619970,0}
};

static const SFG_StrokeVertex ch114st1[] =
{
 {619970,2496607},
 {932046,3432841},
 {1556198,4056993},
 {2180350,4369069},
 {3116577,4369069}
};

static const SFG_StrokeStrip ch114st[] =
{
 {2,ch114st0},
 {5,ch114st1}
};

static const SFG_StrokeChar ch114 = {3243717,2,ch114st};

/* char: 0x73 */

static const SFG_StrokeVertex ch115st0[] =
{
 {3740860,3432841},
 {3428778,4056993},
 {2492550,4369069},
 {1556322,4369069},
 {620095,4056993},
 {308019,3432841},
 {620095,2808683},
 {1244246,2496607},
 {2804626,2184531},
 {3428778,1872455},
 {3740860,1248303},
 {3740860,936227},
 {3428778,312075},
 {2492550,0},
 {1556322,0},
 {620095,312075},
 {308019,936227}
};

static const SFG_StrokeStrip ch115st[] =
{
 {17,ch115st0}
};

static const SFG_StrokeChar ch115 = {4084269,1,ch115st};

/* char: 0x74 */

static const SFG_StrokeVertex ch116st0[] =
{
 {971617,6553600},
 {971617,1248303},
 {1283693,312075},
 {1907844,0},
 {2531996,0}
};

static const SFG_StrokeVertex ch116st1[] =
{
 {35389,4369069},
 {2219920,4369069}
};

static const SFG_StrokeStrip ch116st[] =
{
 {5,ch116st0},
 {2,ch116st1}
};

static const SFG_StrokeChar ch116 = {2576561,2,ch116st};

/* char: 0x75 */

static const SFG_StrokeVertex ch117st0[] =
{
 {619970,4369069},
 {619970,1248303},
 {932046,312075},
 {1556198,0},
 {2492425,0},
 {3116577,312075},
 {4052811,1248303}
};

static const SFG_StrokeVertex ch117st1[] =
{
 {4052811,4369069},
 {4052811,0}
};

static const SFG_StrokeStrip ch117st[] =
{
 {7,ch117st0},
 {2,ch117st1}
};

static const SFG_StrokeChar ch117 = {4663607,2,ch117st};

/* char: 0x76 */

static const SFG_StrokeVertex ch118st0[] =
{
 {117964,4369069},
 {1990420,0}
};

static const SFG_StrokeVertex ch118st1[] =
{
 {3862881,4369069},
 {1990420,0}
};

static const SFG_StrokeStrip ch118st[] =
{
 {2,ch118st0},
 {2,ch118st1}
};

static const SFG_StrokeChar ch118 = {3971671,2,ch118st};

/* char: 0x77 */

static const SFG_StrokeVertex ch119st0[] =
{
 {163840,4369069},
 {1412143,0}
};

static const SFG_StrokeVertex ch119st1[] =
{
 {2660447,4369069},
 {1412143,0}
};

static const SFG_StrokeVertex ch119st2[] =
{
 {2660447,4369069},
 {3908757,0}
};

static const SFG_StrokeVertex ch119st3[] =
{
 {5157060,4369069},
 {3908757,0}
};

static const SFG_StrokeStrip ch119st[] =
{
 {2,ch119st0},
 {2,ch119st1},
 {2,ch119st2},
 {2,ch119st3}
};

static const SFG_StrokeChar ch119 = {5275025,4,ch119st};

/* char: 0x78 */

static const SFG_StrokeVertex ch120st0[] =
{
 {108789,4369069},
 {3541631,0}
};

static const SFG_StrokeVertex ch120st1[] =
{
 {3541631,4369069},
 {108789,0}
};

static const SFG_StrokeStrip ch120st[] =
{
 {2,ch120st0},
 {2,ch120st1}
};

static const SFG_StrokeChar ch120 = {3696296,2,ch120st};

/* char: 0x79 */

static const SFG_StrokeVertex ch121st0[] =
{
 {430040,4369069},
 {2302496,0}
};

static const SFG_StrokeVertex ch121st1[] =
{
 {4174957,4369069},
 {2302496,0},
 {1678344,-1248303},
 {1054192,-1872455},
 {430040,-2184531},
 {117964,-2184531}
};

static const SFG_StrokeStrip ch121st[] =
{
 {2,ch121st0},
 {6,ch121st1}
};

static const SFG_StrokeChar ch121 = {4329623,2,ch121st};

/* char: 0x7a */

static const SFG_StrokeVertex ch122st0[] =
{
 {3723821,4369069},
 {290979,0}
};

static const SFG_StrokeVertex ch122st1[] =
{
 {290979,4369069},
 {3723821,4369069}
};

static const SFG_StrokeVertex ch122st2[] =
{
 {290979,0},
 {3723821,0}
};

static const SFG_StrokeStrip ch122st[] =
{
 {2,ch122st0},
 {2,ch122st1},
 {2,ch122st2}
};

static const SFG_StrokeChar ch122 = {4051501,3,ch122st};

/* char: 0x7b */

static const SFG_StrokeVertex ch123st0[] =
{
 {2044035,7801903},
 {1419883,7489827},
 {1107807,7177752},
 {795731,6553600},
 {795731,5929448},
 {1107807,5305296},
 {1419883,4993220},
 {1731959,4369069},
 {1731959,3744917},
 {1107807,3120758}
};

static const SFG_StrokeVertex ch123st1[] =
{
 {1419883,7489827},
 {1107807,6865676},
 {1107807,6241524},
 {1419883,5617372},
 {1731959,5305296},
 {2044035,4681144},
 {2044035,4056993},
 {1731959,3432841},
 {483655,2808683},
 {1731959,2184531},
 {2044035,1560379},
 {2044035,936227},
 {1731959,312075},
 {1419883,0},
 {1107807,-624151},
 {1107807,-1248303},
 {1419883,-1872455}
};

static const SFG_StrokeVertex ch123st2[] =
{
 {1107807,2496607},
 {1731959,1872455},
 {1731959,1248303},
 {1419883,624151},
 {1107807,312075},
 {795731,-312075},
 {795731,-936227},
 {1107807,-1560379},
 {1419883,-1872455},
 {2044035,-2184531}
};

static const SFG_StrokeStrip ch123st[] =
{
 {10,ch123st0},
 {17,ch123st1},
 {10,ch123st2}
};

static const SFG_StrokeChar ch123 = {2728231,3,ch123st};

/* char: 0x7c */

static const SFG_StrokeVertex ch124st0[] =
{
 {756285,7801903},
 {756285,-2184531}
};

static const SFG_StrokeStrip ch124st[] =
{
 {2,ch124st0}
};

static const SFG_StrokeChar ch124 = {1558446,1,ch124st};

/* char: 0x7d */

static const SFG_StrokeVertex ch125st0[] =
{
 {601620,7801903},
 {1225772,7489827},
 {1537848,7177752},
 {1849924,6553600},
 {1849924,5929448},
 {1537848,5305296},
 {1225772,4993220},
 {913696,4369069},
 {913696,3744917},
 {1537848,3120758}
};

static const SFG_StrokeVertex ch125st1[] =
{
 {1225772,7489827},
 {1537848,6865676},
 {1537848,6241524},
 {1225772,5617372},
 {913696,5305296},
 {601620,4681144},
 {601620,4056993},
 {913696,3432841},
 {2162000,2808683},
 {913696,2184531},
 {601620,1560379},
 {601620,936227},
 {913696,312075},
 {1225772,0},
 {1537848,-624151},
 {1537848,-1248303},
 {1225772,-1872455}
};

static const SFG_StrokeVertex ch125st2[] =
{
 {1537848,2496607},
 {913696,1872455},
 {913696,1248303},
 {1225772,624151},
 {1537848,312075},
 {1849924,-312075},
 {1849924,-936227},
 {1537848,-1560379},
 {1225772,-1872455},
 {601620,-2184531}
};

static const SFG_StrokeStrip ch125st[] =
{
 {10,ch125st0},
 {17,ch125st1},
 {10,ch125st2}
};

static const SFG_StrokeChar ch125 = {2717745,3,ch125st};

/* char: 0x7e */

static const SFG_StrokeVertex ch126st0[] =
{
 {191365,1872455},
 {191365,2496607},
 {503441,3432841},
 {1127592,3744917},
 {1751744,3744917},
 {2375896,3432841},
 {3624206,2496607},
 {4248358,2184531},
 {4872509,2184531},
 {5496661,2496607},
 {5808737,3120758}
};

static const SFG_StrokeVertex ch126st1[] =
{
 {191365,2496607},
 {503441,3120758},
 {1127592,3432841},
 {1751744,3432841},
 {2375896,3120758},
 {3624206,2184531},
 {4248358,1872455},
 {4872509,1872455},
 {5496661,2184531},
 {5808737,3120758},
 {5808737,3744917}
};

static const SFG_StrokeStrip ch126st[] =
{
 {11,ch126st0},
 {11,ch126st1}
};

static const SFG_StrokeChar ch126 = {5981752,2,ch126st};

/* char: 0x7f */

static const SFG_StrokeVertex ch127st0[] =
{
 {3432841,6553600},
 {936227,-2184531}
};

static const SFG_StrokeVertex ch127st1[] =
{
 {1872455,4369069},
 {936227,4056993},
 {312075,3432841},
 {0,2496607},
 {0,1560379},
 {312075,936227},
 {936227,312075},
 {1872455,0},
 {2496607,0},
 {3432841,312075},
 {4056993,936227},
 {4369069,1872455},
 {4369069,2808683},
 {4056993,3432841},
 {3432841,4056993},
 {2496607,4369069},
 {1872455,4369069}
};

static const SFG_StrokeStrip ch127st[] =
{
 {2,ch127st0},
 {17,ch127st1}
};

static const SFG_StrokeChar ch127 = {4369069,2,ch127st};

static const SFG_StrokeChar *chars[] =
{
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 &ch32, &ch33, &ch34, &ch35, &ch36, &ch37, &ch38, &ch39,
 &ch40, &ch41, &ch42, &ch43, &ch44, &ch45, &ch46, &ch47,
 &ch48, &ch49, &ch50, &ch51, &ch52, &ch53, &ch54, &ch55,
 &ch56, &ch57, &ch58, &ch59, &ch60, &ch61, &ch62, &ch63,
 &ch64, &ch65, &ch66, &ch67, &ch68, &ch69, &ch70, &ch71,
 &ch72, &ch73, &ch74, &ch75, &ch76, &ch77, &ch78, &ch79,
 &ch80, &ch81, &ch82, &ch83, &ch84, &ch85, &ch86, &ch87,
 &ch88, &ch89, &ch90, &ch91, &ch92, &ch93, &ch94, &ch95,
 &ch96, &ch97, &ch98, &ch99, &ch100, &ch101, &ch102, &ch103,
 &ch104, &ch105, &ch106, &ch107, &ch108, &ch109, &ch110, &ch111,
 &ch112, &ch113, &ch114, &ch115, &ch116, &ch117, &ch118, &ch119,
 &ch120, &ch121, &ch122, &ch123, &ch124, &ch125, &ch126, &ch127
};

const SFG_StrokeFont fgStrokeRoman = {"Roman",128,9986434,chars};

