/* This file has been automatically generated by the genstroke utility. */

#include "glutes_internal.h"

/* char: 0x20 */

static const SFG_StrokeStrip ch32st[] =
{
  { 0, NULL }
};

static const SFG_StrokeChar ch32 = {6865676,0,ch32st};

/* char: 0x21 */

static const SFG_StrokeVertex ch33st0[] =
{
 {3432841,6553600},
 {3432841,2184531}
};

static const SFG_StrokeVertex ch33st1[] =
{
 {3432841,624151},
 {3120765,312075},
 {3432841,0},
 {3744917,312075},
 {3432841,624151}
};

static const SFG_StrokeStrip ch33st[] =
{
 {2,ch33st0},
 {5,ch33st1}
};

static const SFG_StrokeChar ch33 = {6865676,2,ch33st};

/* char: 0x22 */

static const SFG_StrokeVertex ch34st0[] =
{
 {2184537,6553600},
 {2184537,4369069}
};

static const SFG_StrokeVertex ch34st1[] =
{
 {4681144,6553600},
 {4681144,4369069}
};

static const SFG_StrokeStrip ch34st[] =
{
 {2,ch34st0},
 {2,ch34st1}
};

static const SFG_StrokeChar ch34 = {6865676,2,ch34st};

/* char: 0x23 */

static const SFG_StrokeVertex ch35st0[] =
{
 {3588876,7801903},
 {1404344,-2184531}
};

static const SFG_StrokeVertex ch35st1[] =
{
 {5461337,7801903},
 {3276800,-2184531}
};

static const SFG_StrokeVertex ch35st2[] =
{
 {1404344,3744917},
 {5773407,3744917}
};

static const SFG_StrokeVertex ch35st3[] =
{
 {1092268,1872455},
 {5461337,1872455}
};

static const SFG_StrokeStrip ch35st[] =
{
 {2,ch35st0},
 {2,ch35st1},
 {2,ch35st2},
 {2,ch35st3}
};

static const SFG_StrokeChar ch35 = {6865676,4,ch35st};

/* char: 0x24 */

static const SFG_StrokeVertex ch36st0[] =
{
 {2808683,7801903},
 {2808683,-1248303}
};

static const SFG_StrokeVertex ch36st1[] =
{
 {4056986,7801903},
 {4056986,-1248303}
};

static const SFG_StrokeVertex ch36st2[] =
{
 {5617372,5617372},
 {4993220,6241524},
 {4056986,6553600},
 {2808683,6553600},
 {1872455,6241524},
 {1248303,5617372},
 {1248303,4993220},
 {1560379,4369069},
 {1872455,4056993},
 {2496607,3744917},
 {4369062,3120758},
 {4993220,2808683},
 {5305296,2496607},
 {5617372,1872455},
 {5617372,936227},
 {4993220,312075},
 {4056986,0},
 {2808683,0},
 {1872455,312075},
 {1248303,936227}
};

static const SFG_StrokeStrip ch36st[] =
{
 {2,ch36st0},
 {2,ch36st1},
 {20,ch36st2}
};

static const SFG_StrokeChar ch36 = {6865676,3,ch36st};

/* char: 0x25 */

static const SFG_StrokeVertex ch37st0[] =
{
 {6241524,6553600},
 {624151,0}
};

static const SFG_StrokeVertex ch37st1[] =
{
 {2184531,6553600},
 {2808683,5929448},
 {2808683,5305296},
 {2496607,4681144},
 {1872455,4369069},
 {1248303,4369069},
 {624151,4993220},
 {624151,5617372},
 {936227,6241524},
 {1560379,6553600},
 {2184531,6553600},
 {2808683,6241524},
 {3744910,5929448},
 {4681144,5929448},
 {5617372,6241524},
 {6241524,6553600}
};

static const SFG_StrokeVertex ch37st2[] =
{
 {4993220,2184531},
 {4369069,1872455},
 {4056993,1248303},
 {4056993,624151},
 {4681144,0},
 {5305296,0},
 {5929448,312075},
 {6241524,936227},
 {6241524,1560379},
 {5617372,2184531},
 {4993220,2184531}
};

static const SFG_StrokeStrip ch37st[] =
{
 {2,ch37st0},
 {16,ch37st1},
 {11,ch37st2}
};

static const SFG_StrokeChar ch37 = {6865676,3,ch37st};

/* char: 0x26 */

static const SFG_StrokeVertex ch38st0[] =
{
 {6553600,3744917},
 {6553600,4056993},
 {6241524,4369069},
 {5929448,4369069},
 {5617372,4056993},
 {5305296,3432841},
 {4681144,1872455},
 {4056993,936227},
 {3432834,312075},
 {2808683,0},
 {1560379,0},
 {936227,312075},
 {624151,624151},
 {312075,1248303},
 {312075,1872455},
 {624151,2496607},
 {936227,2808683},
 {3120758,4056993},
 {3432834,4369069},
 {3744917,4993220},
 {3744917,5617372},
 {3432834,6241524},
 {2808683,6553600},
 {2184531,6241524},
 {1872455,5617372},
 {1872455,4993220},
 {2184531,4056993},
 {2808683,3120758},
 {4369069,936227},
 {4993220,312075},
 {5617372,0},
 {6241524,0},
 {6553600,312075},
 {6553600,624151}
};

static const SFG_StrokeStrip ch38st[] =
{
 {34,ch38st0}
};

static const SFG_StrokeChar ch38 = {6865676,1,ch38st};

/* char: 0x27 */

static const SFG_StrokeVertex ch39st0[] =
{
 {3432841,6553600},
 {3432841,4369069}
};

static const SFG_StrokeStrip ch39st[] =
{
 {2,ch39st0}
};

static const SFG_StrokeChar ch39 = {6865676,1,ch39st};

/* char: 0x28 */

static const SFG_StrokeVertex ch40st0[] =
{
 {4525103,7801903},
 {3900951,7177752},
 {3276800,6241524},
 {2652648,4993220},
 {2340572,3432841},
 {2340572,2184531},
 {2652648,624151},
 {3276800,-624151},
 {3900951,-1560379},
 {4525103,-2184531}
};

static const SFG_StrokeStrip ch40st[] =
{
 {10,ch40st0}
};

static const SFG_StrokeChar ch40 = {6865676,1,ch40st};

/* char: 0x29 */

static const SFG_StrokeVertex ch41st0[] =
{
 {2340572,7801903},
 {2964724,7177752},
 {3588876,6241524},
 {4213027,4993220},
 {4525103,3432841},
 {4525103,2184531},
 {4213027,624151},
 {3588876,-624151},
 {2964724,-1560379},
 {2340572,-2184531}
};

static const SFG_StrokeStrip ch41st[] =
{
 {10,ch41st0}
};

static const SFG_StrokeChar ch41 = {6865676,1,ch41st};

/* char: 0x2a */

static const SFG_StrokeVertex ch42st0[] =
{
 {3432841,4681144},
 {3432841,936227}
};

static const SFG_StrokeVertex ch42st1[] =
{
 {1872461,3744917},
 {4993220,1872455}
};

static const SFG_StrokeVertex ch42st2[] =
{
 {4993220,3744917},
 {1872461,1872455}
};

static const SFG_StrokeStrip ch42st[] =
{
 {2,ch42st0},
 {2,ch42st1},
 {2,ch42st2}
};

static const SFG_StrokeChar ch42 = {6865676,3,ch42st};

/* char: 0x2b */

static const SFG_StrokeVertex ch43st0[] =
{
 {3432834,5617372},
 {3432834,0}
};

static const SFG_StrokeVertex ch43st1[] =
{
 {624151,2808683},
 {6241524,2808683}
};

static const SFG_StrokeStrip ch43st[] =
{
 {2,ch43st0},
 {2,ch43st1}
};

static const SFG_StrokeChar ch43 = {6865676,2,ch43st};

/* char: 0x2c */

static const SFG_StrokeVertex ch44st0[] =
{
 {3744917,312075},
 {3432841,0},
 {3120765,312075},
 {3432841,624151},
 {3744917,312075},
 {3744917,-312075},
 {3432841,-936227},
 {3120765,-1248303}
};

static const SFG_StrokeStrip ch44st[] =
{
 {8,ch44st0}
};

static const SFG_StrokeChar ch44 = {6865676,1,ch44st};

/* char: 0x2d */

static const SFG_StrokeVertex ch45st0[] =
{
 {624151,2808683},
 {6241524,2808683}
};

static const SFG_StrokeStrip ch45st[] =
{
 {2,ch45st0}
};

static const SFG_StrokeChar ch45 = {6865676,1,ch45st};

/* char: 0x2e */

static const SFG_StrokeVertex ch46st0[] =
{
 {3432841,624151},
 {3120765,312075},
 {3432841,0},
 {3744917,312075},
 {3432841,624151}
};

static const SFG_StrokeStrip ch46st[] =
{
 {5,ch46st0}
};

static const SFG_StrokeChar ch46 = {6865676,1,ch46st};

/* char: 0x2f */

static const SFG_StrokeVertex ch47st0[] =
{
 {1248303,-936227},
 {5617372,6553600}
};

static const SFG_StrokeStrip ch47st[] =
{
 {2,ch47st0}
};

static const SFG_StrokeChar ch47 = {6865676,1,ch47st};

/* char: 0x30 */

static const SFG_StrokeVertex ch48st0[] =
{
 {3120758,6553600},
 {2184531,6241524},
 {1560379,5305296},
 {1248303,3744917},
 {1248303,2808683},
 {1560379,1248303},
 {2184531,312075},
 {3120758,0},
 {3744910,0},
 {4681144,312075},
 {5305296,1248303},
 {5617372,2808683},
 {5617372,3744917},
 {5305296,5305296},
 {4681144,6241524},
 {3744910,6553600},
 {3120758,6553600}
};

static const SFG_StrokeStrip ch48st[] =
{
 {17,ch48st0}
};

static const SFG_StrokeChar ch48 = {6865676,1,ch48st};

/* char: 0x31 */

static const SFG_StrokeVertex ch49st0[] =
{
 {2652648,5305296},
 {3276800,5617372},
 {4213027,6553600},
 {4213027,0}
};

static const SFG_StrokeStrip ch49st[] =
{
 {4,ch49st0}
};

static const SFG_StrokeChar ch49 = {6865676,1,ch49st};

/* char: 0x32 */

static const SFG_StrokeVertex ch50st0[] =
{
 {1560379,4993220},
 {1560379,5305296},
 {1872455,5929448},
 {2184531,6241524},
 {2808683,6553600},
 {4056986,6553600},
 {4681144,6241524},
 {4993220,5929448},
 {5305296,5305296},
 {5305296,4681144},
 {4993220,4056993},
 {4369062,3120758},
 {1248303,0},
 {5617372,0}
};

static const SFG_StrokeStrip ch50st[] =
{
 {14,ch50st0}
};

static const SFG_StrokeChar ch50 = {6865676,1,ch50st};

/* char: 0x33 */

static const SFG_StrokeVertex ch51st0[] =
{
 {1872455,6553600},
 {5305296,6553600},
 {3432834,4056993},
 {4369062,4056993},
 {4993220,3744917},
 {5305296,3432841},
 {5617372,2496607},
 {5617372,1872455},
 {5305296,936227},
 {4681144,312075},
 {3744910,0},
 {2808683,0},
 {1872455,312075},
 {1560379,624151},
 {1248303,1248303}
};

static const SFG_StrokeStrip ch51st[] =
{
 {15,ch51st0}
};

static const SFG_StrokeChar ch51 = {6865676,1,ch51st};

/* char: 0x34 */

static const SFG_StrokeVertex ch52st0[] =
{
 {4213027,6553600},
 {1092268,2184531},
 {5773407,2184531}
};

static const SFG_StrokeVertex ch52st1[] =
{
 {4213027,6553600},
 {4213027,0}
};

static const SFG_StrokeStrip ch52st[] =
{
 {3,ch52st0},
 {2,ch52st1}
};

static const SFG_StrokeChar ch52 = {6865676,2,ch52st};

/* char: 0x35 */

static const SFG_StrokeVertex ch53st0[] =
{
 {4993220,6553600},
 {1872455,6553600},
 {1560379,3744917},
 {1872455,4056993},
 {2808683,4369069},
 {3744910,4369069},
 {4681144,4056993},
 {5305296,3432841},
 {5617372,2496607},
 {5617372,1872455},
 {5305296,936227},
 {4681144,312075},
 {3744910,0},
 {2808683,0},
 {1872455,312075},
 {1560379,624151},
 {1248303,1248303}
};

static const SFG_StrokeStrip ch53st[] =
{
 {17,ch53st0}
};

static const SFG_StrokeChar ch53 = {6865676,1,ch53st};

/* char: 0x36 */

static const SFG_StrokeVertex ch54st0[] =
{
 {5149255,5617372},
 {4837186,6241524},
 {3900951,6553600},
 {3276800,6553600},
 {2340572,6241524},
 {1716420,5305296},
 {1404344,3744917},
 {1404344,2184531},
 {1716420,936227},
 {2340572,312075},
 {3276800,0},
 {3588876,0},
 {4525103,312075},
 {5149255,936227},
 {5461337,1872455},
 {5461337,2184531},
 {5149255,3120758},
 {4525103,3744917},
 {3588876,4056993},
 {3276800,4056993},
 {2340572,3744917},
 {1716420,3120758},
 {1404344,2184531}
};

static const SFG_StrokeStrip ch54st[] =
{
 {23,ch54st0}
};

static const SFG_StrokeChar ch54 = {6865676,1,ch54st};

/* char: 0x37 */

static const SFG_StrokeVertex ch55st0[] =
{
 {5617372,6553600},
 {2496607,0}
};

static const SFG_StrokeVertex ch55st1[] =
{
 {1248303,6553600},
 {5617372,6553600}
};

static const SFG_StrokeStrip ch55st[] =
{
 {2,ch55st0},
 {2,ch55st1}
};

static const SFG_StrokeChar ch55 = {6865676,2,ch55st};

/* char: 0x38 */

static const SFG_StrokeVertex ch56st0[] =
{
 {2808683,6553600},
 {1872455,6241524},
 {1560379,5617372},
 {1560379,4993220},
 {1872455,4369069},
 {2496607,4056993},
 {3744910,3744917},
 {4681144,3432841},
 {5305296,2808683},
 {5617372,2184531},
 {5617372,1248303},
 {5305296,624151},
 {4993220,312075},
 {4056986,0},
 {2808683,0},
 {1872455,312075},
 {1560379,624151},
 {1248303,1248303},
 {1248303,2184531},
 {1560379,2808683},
 {2184531,3432841},
 {3120758,3744917},
 {4369062,4056993},
 {4993220,4369069},
 {5305296,4993220},
 {5305296,5617372},
 {4993220,6241524},
 {4056986,6553600},
 {2808683,6553600}
};

static const SFG_StrokeStrip ch56st[] =
{
 {29,ch56st0}
};

static const SFG_StrokeChar ch56 = {6865676,1,ch56st};

/* char: 0x39 */

static const SFG_StrokeVertex ch57st0[] =
{
 {5461337,4369069},
 {5149255,3432841},
 {4525103,2808683},
 {3588876,2496607},
 {3276800,2496607},
 {2340572,2808683},
 {1716420,3432841},
 {1404344,4369069},
 {1404344,4681144},
 {1716420,5617372},
 {2340572,6241524},
 {3276800,6553600},
 {3588876,6553600},
 {4525103,6241524},
 {5149255,5617372},
 {5461337,4369069},
 {5461337,2808683},
 {5149255,1248303},
 {4525103,312075},
 {3588876,0},
 {2964724,0},
 {2028496,312075},
 {1716420,936227}
};

static const SFG_StrokeStrip ch57st[] =
{
 {23,ch57st0}
};

static const SFG_StrokeChar ch57 = {6865676,1,ch57st};

/* char: 0x3a */

static const SFG_StrokeVertex ch58st0[] =
{
 {3432841,4369069},
 {3120765,4056993},
 {3432841,3744917},
 {3744917,4056993},
 {3432841,4369069}
};

static const SFG_StrokeVertex ch58st1[] =
{
 {3432841,624151},
 {3120765,312075},
 {3432841,0},
 {3744917,312075},
 {3432841,624151}
};

static const SFG_StrokeStrip ch58st[] =
{
 {5,ch58st0},
 {5,ch58st1}
};

static const SFG_StrokeChar ch58 = {6865676,2,ch58st};

/* char: 0x3b */

static const SFG_StrokeVertex ch59st0[] =
{
 {3432841,4369069},
 {3120765,4056993},
 {3432841,3744917},
 {3744917,4056993},
 {3432841,4369069}
};

static const SFG_StrokeVertex ch59st1[] =
{
 {3744917,312075},
 {3432841,0},
 {3120765,312075},
 {3432841,624151},
 {3744917,312075},
 {3744917,-312075},
 {3432841,-936227},
 {3120765,-1248303}
};

static const SFG_StrokeStrip ch59st[] =
{
 {5,ch59st0},
 {8,ch59st1}
};

static const SFG_StrokeChar ch59 = {6865676,2,ch59st};

/* char: 0x3c */

static const SFG_StrokeVertex ch60st0[] =
{
 {5929448,5617372},
 {936227,2808683},
 {5929448,0}
};

static const SFG_StrokeStrip ch60st[] =
{
 {3,ch60st0}
};

static const SFG_StrokeChar ch60 = {6865676,1,ch60st};

/* char: 0x3d */

static const SFG_StrokeVertex ch61st0[] =
{
 {624151,3744917},
 {6241524,3744917}
};

static const SFG_StrokeVertex ch61st1[] =
{
 {624151,1872455},
 {6241524,1872455}
};

static const SFG_StrokeStrip ch61st[] =
{
 {2,ch61st0},
 {2,ch61st1}
};

static const SFG_StrokeChar ch61 = {6865676,2,ch61st};

/* char: 0x3e */

static const SFG_StrokeVertex ch62st0[] =
{
 {936227,5617372},
 {5929448,2808683},
 {936227,0}
};

static const SFG_StrokeStrip ch62st[] =
{
 {3,ch62st0}
};

static const SFG_StrokeChar ch62 = {6865676,1,ch62st};

/* char: 0x3f */

static const SFG_StrokeVertex ch63st0[] =
{
 {1560379,4993220},
 {1560379,5305296},
 {1872455,5929448},
 {2184531,6241524},
 {2808683,6553600},
 {4056986,6553600},
 {4681138,6241524},
 {4993220,5929448},
 {5305296,5305296},
 {5305296,4681144},
 {4993220,4056993},
 {4681138,3744917},
 {3432834,3120758},
 {3432834,2184531}
};

static const SFG_StrokeVertex ch63st1[] =
{
 {3432834,624151},
 {3120758,312075},
 {3432834,0},
 {3744910,312075},
 {3432834,624151}
};

static const SFG_StrokeStrip ch63st[] =
{
 {14,ch63st0},
 {5,ch63st1}
};

static const SFG_StrokeChar ch63 = {6865676,2,ch63st};

/* char: 0x40 */

static const SFG_StrokeVertex ch64st0[] =
{
 {4213027,3432841},
 {3588876,3744917},
 {2964724,3744917},
 {2652648,3120758},
 {2652648,2808683},
 {2964724,2184531},
 {3588876,2184531},
 {4213027,2496607}
};

static const SFG_StrokeVertex ch64st1[] =
{
 {4213027,3744917},
 {4213027,2496607},
 {4525103,2184531},
 {5149255,2184531},
 {5461337,2808683},
 {5461337,3120758},
 {5149255,4056993},
 {4525103,4681144},
 {3588876,4993220},
 {3276800,4993220},
 {2340572,4681144},
 {1716420,4056993},
 {1404344,3120758},
 {1404344,2808683},
 {1716420,1872455},
 {2340572,1248303},
 {3276800,936227},
 {3588876,936227},
 {4525103,1248303}
};

static const SFG_StrokeStrip ch64st[] =
{
 {8,ch64st0},
 {19,ch64st1}
};

static const SFG_StrokeChar ch64 = {6865676,2,ch64st};

/* char: 0x41 */

static const SFG_StrokeVertex ch65st0[] =
{
 {3432834,6553600},
 {936227,0}
};

static const SFG_StrokeVertex ch65st1[] =
{
 {3432834,6553600},
 {5929448,0}
};

static const SFG_StrokeVertex ch65st2[] =
{
 {1872455,2184531},
 {4993220,2184531}
};

static const SFG_StrokeStrip ch65st[] =
{
 {2,ch65st0},
 {2,ch65st1},
 {2,ch65st2}
};

static const SFG_StrokeChar ch65 = {6865676,3,ch65st};

/* char: 0x42 */

static const SFG_StrokeVertex ch66st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch66st1[] =
{
 {1248303,6553600},
 {4056986,6553600},
 {4993220,6241524},
 {5305296,5929448},
 {5617372,5305296},
 {5617372,4681144},
 {5305296,4056993},
 {4993220,3744917},
 {4056986,3432841}
};

static const SFG_StrokeVertex ch66st2[] =
{
 {1248303,3432841},
 {4056986,3432841},
 {4993220,3120758},
 {5305296,2808683},
 {5617372,2184531},
 {5617372,1248303},
 {5305296,624151},
 {4993220,312075},
 {4056986,0},
 {1248303,0}
};

static const SFG_StrokeStrip ch66st[] =
{
 {2,ch66st0},
 {9,ch66st1},
 {10,ch66st2}
};

static const SFG_StrokeChar ch66 = {6865676,3,ch66st};

/* char: 0x43 */

static const SFG_StrokeVertex ch67st0[] =
{
 {5773407,4993220},
 {5461337,5617372},
 {4837186,6241524},
 {4213027,6553600},
 {2964724,6553600},
 {2340572,6241524},
 {1716420,5617372},
 {1404344,4993220},
 {1092268,4056993},
 {1092268,2496607},
 {1404344,1560379},
 {1716420,936227},
 {2340572,312075},
 {2964724,0},
 {4213027,0},
 {4837186,312075},
 {5461337,936227},
 {5773407,1560379}
};

static const SFG_StrokeStrip ch67st[] =
{
 {18,ch67st0}
};

static const SFG_StrokeChar ch67 = {6865676,1,ch67st};

/* char: 0x44 */

static const SFG_StrokeVertex ch68st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch68st1[] =
{
 {1248303,6553600},
 {3432834,6553600},
 {4369062,6241524},
 {4993220,5617372},
 {5305296,4993220},
 {5617372,4056993},
 {5617372,2496607},
 {5305296,1560379},
 {4993220,936227},
 {4369062,312075},
 {3432834,0},
 {1248303,0}
};

static const SFG_StrokeStrip ch68st[] =
{
 {2,ch68st0},
 {12,ch68st1}
};

static const SFG_StrokeChar ch68 = {6865676,2,ch68st};

/* char: 0x45 */

static const SFG_StrokeVertex ch69st0[] =
{
 {1404344,6553600},
 {1404344,0}
};

static const SFG_StrokeVertex ch69st1[] =
{
 {1404344,6553600},
 {5461337,6553600}
};

static const SFG_StrokeVertex ch69st2[] =
{
 {1404344,3432841},
 {3900951,3432841}
};

static const SFG_StrokeVertex ch69st3[] =
{
 {1404344,0},
 {5461337,0}
};

static const SFG_StrokeStrip ch69st[] =
{
 {2,ch69st0},
 {2,ch69st1},
 {2,ch69st2},
 {2,ch69st3}
};

static const SFG_StrokeChar ch69 = {6865676,4,ch69st};

/* char: 0x46 */

static const SFG_StrokeVertex ch70st0[] =
{
 {1404344,6553600},
 {1404344,0}
};

static const SFG_StrokeVertex ch70st1[] =
{
 {1404344,6553600},
 {5461337,6553600}
};

static const SFG_StrokeVertex ch70st2[] =
{
 {1404344,3432841},
 {3900951,3432841}
};

static const SFG_StrokeStrip ch70st[] =
{
 {2,ch70st0},
 {2,ch70st1},
 {2,ch70st2}
};

static const SFG_StrokeChar ch70 = {6865676,3,ch70st};

/* char: 0x47 */

static const SFG_StrokeVertex ch71st0[] =
{
 {5773407,4993220},
 {5461337,5617372},
 {4837186,6241524},
 {4213027,6553600},
 {2964724,6553600},
 {2340572,6241524},
 {1716420,5617372},
 {1404344,4993220},
 {1092268,4056993},
 {1092268,2496607},
 {1404344,1560379},
 {1716420,936227},
 {2340572,312075},
 {2964724,0},
 {4213027,0},
 {4837186,312075},
 {5461337,936227},
 {5773407,1560379},
 {5773407,2496607}
};

static const SFG_StrokeVertex ch71st1[] =
{
 {4213027,2496607},
 {5773407,2496607}
};

static const SFG_StrokeStrip ch71st[] =
{
 {19,ch71st0},
 {2,ch71st1}
};

static const SFG_StrokeChar ch71 = {6865676,2,ch71st};

/* char: 0x48 */

static const SFG_StrokeVertex ch72st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch72st1[] =
{
 {5617372,6553600},
 {5617372,0}
};

static const SFG_StrokeVertex ch72st2[] =
{
 {1248303,3432841},
 {5617372,3432841}
};

static const SFG_StrokeStrip ch72st[] =
{
 {2,ch72st0},
 {2,ch72st1},
 {2,ch72st2}
};

static const SFG_StrokeChar ch72 = {6865676,3,ch72st};

/* char: 0x49 */

static const SFG_StrokeVertex ch73st0[] =
{
 {3432841,6553600},
 {3432841,0}
};

static const SFG_StrokeStrip ch73st[] =
{
 {2,ch73st0}
};

static const SFG_StrokeChar ch73 = {6865676,1,ch73st};

/* char: 0x4a */

static const SFG_StrokeVertex ch74st0[] =
{
 {4993220,6553600},
 {4993220,1560379},
 {4681144,624151},
 {4369069,312075},
 {3744917,0},
 {3120765,0},
 {2496613,312075},
 {2184537,624151},
 {1872461,1560379},
 {1872461,2184531}
};

static const SFG_StrokeStrip ch74st[] =
{
 {10,ch74st0}
};

static const SFG_StrokeChar ch74 = {6865676,1,ch74st};

/* char: 0x4b */

static const SFG_StrokeVertex ch75st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch75st1[] =
{
 {5617372,6553600},
 {1248303,2184531}
};

static const SFG_StrokeVertex ch75st2[] =
{
 {2808683,3744917},
 {5617372,0}
};

static const SFG_StrokeStrip ch75st[] =
{
 {2,ch75st0},
 {2,ch75st1},
 {2,ch75st2}
};

static const SFG_StrokeChar ch75 = {6865676,3,ch75st};

/* char: 0x4c */

static const SFG_StrokeVertex ch76st0[] =
{
 {1560379,6553600},
 {1560379,0}
};

static const SFG_StrokeVertex ch76st1[] =
{
 {1560379,0},
 {5305296,0}
};

static const SFG_StrokeStrip ch76st[] =
{
 {2,ch76st0},
 {2,ch76st1}
};

static const SFG_StrokeChar ch76 = {6865676,2,ch76st};

/* char: 0x4d */

static const SFG_StrokeVertex ch77st0[] =
{
 {936227,6553600},
 {936227,0}
};

static const SFG_StrokeVertex ch77st1[] =
{
 {936227,6553600},
 {3432834,0}
};

static const SFG_StrokeVertex ch77st2[] =
{
 {5929448,6553600},
 {3432834,0}
};

static const SFG_StrokeVertex ch77st3[] =
{
 {5929448,6553600},
 {5929448,0}
};

static const SFG_StrokeStrip ch77st[] =
{
 {2,ch77st0},
 {2,ch77st1},
 {2,ch77st2},
 {2,ch77st3}
};

static const SFG_StrokeChar ch77 = {6865676,4,ch77st};

/* char: 0x4e */

static const SFG_StrokeVertex ch78st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch78st1[] =
{
 {1248303,6553600},
 {5617372,0}
};

static const SFG_StrokeVertex ch78st2[] =
{
 {5617372,6553600},
 {5617372,0}
};

static const SFG_StrokeStrip ch78st[] =
{
 {2,ch78st0},
 {2,ch78st1},
 {2,ch78st2}
};

static const SFG_StrokeChar ch78 = {6865676,3,ch78st};

/* char: 0x4f */

static const SFG_StrokeVertex ch79st0[] =
{
 {2808683,6553600},
 {2184531,6241524},
 {1560379,5617372},
 {1248303,4993220},
 {936227,4056993},
 {936227,2496607},
 {1248303,1560379},
 {1560379,936227},
 {2184531,312075},
 {2808683,0},
 {4056986,0},
 {4681144,312075},
 {5305296,936227},
 {5617372,1560379},
 {5929448,2496607},
 {5929448,4056993},
 {5617372,4993220},
 {5305296,5617372},
 {4681144,6241524},
 {4056986,6553600},
 {2808683,6553600}
};

static const SFG_StrokeStrip ch79st[] =
{
 {21,ch79st0}
};

static const SFG_StrokeChar ch79 = {6865676,1,ch79st};

/* char: 0x50 */

static const SFG_StrokeVertex ch80st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch80st1[] =
{
 {1248303,6553600},
 {4056986,6553600},
 {4993220,6241524},
 {5305296,5929448},
 {5617372,5305296},
 {5617372,4369069},
 {5305296,3744917},
 {4993220,3432841},
 {4056986,3120758},
 {1248303,3120758}
};

static const SFG_StrokeStrip ch80st[] =
{
 {2,ch80st0},
 {10,ch80st1}
};

static const SFG_StrokeChar ch80 = {6865676,2,ch80st};

/* char: 0x51 */

static const SFG_StrokeVertex ch81st0[] =
{
 {2808683,6553600},
 {2184531,6241524},
 {1560379,5617372},
 {1248303,4993220},
 {936227,4056993},
 {936227,2496607},
 {1248303,1560379},
 {1560379,936227},
 {2184531,312075},
 {2808683,0},
 {4056986,0},
 {4681144,312075},
 {5305296,936227},
 {5617372,1560379},
 {5929448,2496607},
 {5929448,4056993},
 {5617372,4993220},
 {5305296,5617372},
 {4681144,6241524},
 {4056986,6553600},
 {2808683,6553600}
};

static const SFG_StrokeVertex ch81st1[] =
{
 {3744910,1248303},
 {5617372,-624151}
};

static const SFG_StrokeStrip ch81st[] =
{
 {21,ch81st0},
 {2,ch81st1}
};

static const SFG_StrokeChar ch81 = {6865676,2,ch81st};

/* char: 0x52 */

static const SFG_StrokeVertex ch82st0[] =
{
 {1248303,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch82st1[] =
{
 {1248303,6553600},
 {4056986,6553600},
 {4993220,6241524},
 {5305296,5929448},
 {5617372,5305296},
 {5617372,4681144},
 {5305296,4056993},
 {4993220,3744917},
 {4056986,3432841},
 {1248303,3432841}
};

static const SFG_StrokeVertex ch82st2[] =
{
 {3432834,3432841},
 {5617372,0}
};

static const SFG_StrokeStrip ch82st[] =
{
 {2,ch82st0},
 {10,ch82st1},
 {2,ch82st2}
};

static const SFG_StrokeChar ch82 = {6865676,3,ch82st};

/* char: 0x53 */

static const SFG_StrokeVertex ch83st0[] =
{
 {5617372,5617372},
 {4993220,6241524},
 {4056986,6553600},
 {2808683,6553600},
 {1872455,6241524},
 {1248303,5617372},
 {1248303,4993220},
 {1560379,4369069},
 {1872455,4056993},
 {2496607,3744917},
 {4369062,3120758},
 {4993220,2808683},
 {5305296,2496607},
 {5617372,1872455},
 {5617372,936227},
 {4993220,312075},
 {4056986,0},
 {2808683,0},
 {1872455,312075},
 {1248303,936227}
};

static const SFG_StrokeStrip ch83st[] =
{
 {20,ch83st0}
};

static const SFG_StrokeChar ch83 = {6865676,1,ch83st};

/* char: 0x54 */

static const SFG_StrokeVertex ch84st0[] =
{
 {3432834,6553600},
 {3432834,0}
};

static const SFG_StrokeVertex ch84st1[] =
{
 {1248303,6553600},
 {5617372,6553600}
};

static const SFG_StrokeStrip ch84st[] =
{
 {2,ch84st0},
 {2,ch84st1}
};

static const SFG_StrokeChar ch84 = {6865676,2,ch84st};

/* char: 0x55 */

static const SFG_StrokeVertex ch85st0[] =
{
 {1248303,6553600},
 {1248303,1872455},
 {1560379,936227},
 {2184531,312075},
 {3120758,0},
 {3744910,0},
 {4681144,312075},
 {5305296,936227},
 {5617372,1872455},
 {5617372,6553600}
};

static const SFG_StrokeStrip ch85st[] =
{
 {10,ch85st0}
};

static const SFG_StrokeChar ch85 = {6865676,1,ch85st};

/* char: 0x56 */

static const SFG_StrokeVertex ch86st0[] =
{
 {936227,6553600},
 {3432834,0}
};

static const SFG_StrokeVertex ch86st1[] =
{
 {5929448,6553600},
 {3432834,0}
};

static const SFG_StrokeStrip ch86st[] =
{
 {2,ch86st0},
 {2,ch86st1}
};

static const SFG_StrokeChar ch86 = {6865676,2,ch86st};

/* char: 0x57 */

static const SFG_StrokeVertex ch87st0[] =
{
 {312075,6553600},
 {1872455,0}
};

static const SFG_StrokeVertex ch87st1[] =
{
 {3432834,6553600},
 {1872455,0}
};

static const SFG_StrokeVertex ch87st2[] =
{
 {3432834,6553600},
 {4993220,0}
};

static const SFG_StrokeVertex ch87st3[] =
{
 {6553600,6553600},
 {4993220,0}
};

static const SFG_StrokeStrip ch87st[] =
{
 {2,ch87st0},
 {2,ch87st1},
 {2,ch87st2},
 {2,ch87st3}
};

static const SFG_StrokeChar ch87 = {6865676,4,ch87st};

/* char: 0x58 */

static const SFG_StrokeVertex ch88st0[] =
{
 {1248303,6553600},
 {5617372,0}
};

static const SFG_StrokeVertex ch88st1[] =
{
 {5617372,6553600},
 {1248303,0}
};

static const SFG_StrokeStrip ch88st[] =
{
 {2,ch88st0},
 {2,ch88st1}
};

static const SFG_StrokeChar ch88 = {6865676,2,ch88st};

/* char: 0x59 */

static const SFG_StrokeVertex ch89st0[] =
{
 {936227,6553600},
 {3432834,3432841},
 {3432834,0}
};

static const SFG_StrokeVertex ch89st1[] =
{
 {5929448,6553600},
 {3432834,3432841}
};

static const SFG_StrokeStrip ch89st[] =
{
 {3,ch89st0},
 {2,ch89st1}
};

static const SFG_StrokeChar ch89 = {6865676,2,ch89st};

/* char: 0x5a */

static const SFG_StrokeVertex ch90st0[] =
{
 {5617372,6553600},
 {1248303,0}
};

static const SFG_StrokeVertex ch90st1[] =
{
 {1248303,6553600},
 {5617372,6553600}
};

static const SFG_StrokeVertex ch90st2[] =
{
 {1248303,0},
 {5617372,0}
};

static const SFG_StrokeStrip ch90st[] =
{
 {2,ch90st0},
 {2,ch90st1},
 {2,ch90st2}
};

static const SFG_StrokeChar ch90 = {6865676,3,ch90st};

/* char: 0x5b */

static const SFG_StrokeVertex ch91st0[] =
{
 {2340572,7801903},
 {2340572,-2184531}
};

static const SFG_StrokeVertex ch91st1[] =
{
 {2652648,7801903},
 {2652648,-2184531}
};

static const SFG_StrokeVertex ch91st2[] =
{
 {2340572,7801903},
 {4525103,7801903}
};

static const SFG_StrokeVertex ch91st3[] =
{
 {2340572,-2184531},
 {4525103,-2184531}
};

static const SFG_StrokeStrip ch91st[] =
{
 {2,ch91st0},
 {2,ch91st1},
 {2,ch91st2},
 {2,ch91st3}
};

static const SFG_StrokeChar ch91 = {6865676,4,ch91st};

/* char: 0x5c */

static const SFG_StrokeVertex ch92st0[] =
{
 {1248303,6553600},
 {5617372,-936227}
};

static const SFG_StrokeStrip ch92st[] =
{
 {2,ch92st0}
};

static const SFG_StrokeChar ch92 = {6865676,1,ch92st};

/* char: 0x5d */

static const SFG_StrokeVertex ch93st0[] =
{
 {4213027,7801903},
 {4213027,-2184531}
};

static const SFG_StrokeVertex ch93st1[] =
{
 {4525103,7801903},
 {4525103,-2184531}
};

static const SFG_StrokeVertex ch93st2[] =
{
 {2340572,7801903},
 {4525103,7801903}
};

static const SFG_StrokeVertex ch93st3[] =
{
 {2340572,-2184531},
 {4525103,-2184531}
};

static const SFG_StrokeStrip ch93st[] =
{
 {2,ch93st0},
 {2,ch93st1},
 {2,ch93st2},
 {2,ch93st3}
};

static const SFG_StrokeChar ch93 = {6865676,4,ch93st};

/* char: 0x5e */

static const SFG_StrokeVertex ch94st0[] =
{
 {3432834,7177752},
 {936227,2808683}
};

static const SFG_StrokeVertex ch94st1[] =
{
 {3432834,7177752},
 {5929448,2808683}
};

static const SFG_StrokeStrip ch94st[] =
{
 {2,ch94st0},
 {2,ch94st1}
};

static const SFG_StrokeChar ch94 = {6865676,2,ch94st};

/* char: 0x5f */

static const SFG_StrokeVertex ch95st0[] =
{
 {0,-2184531},
 {6865676,-2184531},
 {6865676,-1872455},
 {0,-1872455},
 {0,-2184531}
};

static const SFG_StrokeStrip ch95st[] =
{
 {5,ch95st0}
};

static const SFG_StrokeChar ch95 = {6865676,1,ch95st};

/* char: 0x60 */

static const SFG_StrokeVertex ch96st0[] =
{
 {2808689,6553600},
 {4369069,4681144}
};

static const SFG_StrokeVertex ch96st1[] =
{
 {2808689,6553600},
 {2496613,6241524},
 {4369069,4681144}
};

static const SFG_StrokeStrip ch96st[] =
{
 {2,ch96st0},
 {3,ch96st1}
};

static const SFG_StrokeChar ch96 = {6865676,2,ch96st};

/* char: 0x61 */

static const SFG_StrokeVertex ch97st0[] =
{
 {5305296,4369069},
 {5305296,0}
};

static const SFG_StrokeVertex ch97st1[] =
{
 {5305296,3432841},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch97st[] =
{
 {2,ch97st0},
 {14,ch97st1}
};

static const SFG_StrokeChar ch97 = {6865676,2,ch97st};

/* char: 0x62 */

static const SFG_StrokeVertex ch98st0[] =
{
 {1560379,6553600},
 {1560379,0}
};

static const SFG_StrokeVertex ch98st1[] =
{
 {1560379,3432841},
 {2184531,4056993},
 {2808683,4369069},
 {3744910,4369069},
 {4369062,4056993},
 {4993220,3432841},
 {5305296,2496607},
 {5305296,1872455},
 {4993220,936227},
 {4369062,312075},
 {3744910,0},
 {2808683,0},
 {2184531,312075},
 {1560379,936227}
};

static const SFG_StrokeStrip ch98st[] =
{
 {2,ch98st0},
 {14,ch98st1}
};

static const SFG_StrokeChar ch98 = {6865676,2,ch98st};

/* char: 0x63 */

static const SFG_StrokeVertex ch99st0[] =
{
 {5305296,3432841},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch99st[] =
{
 {14,ch99st0}
};

static const SFG_StrokeChar ch99 = {6865676,1,ch99st};

/* char: 0x64 */

static const SFG_StrokeVertex ch100st0[] =
{
 {5305296,6553600},
 {5305296,0}
};

static const SFG_StrokeVertex ch100st1[] =
{
 {5305296,3432841},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch100st[] =
{
 {2,ch100st0},
 {14,ch100st1}
};

static const SFG_StrokeChar ch100 = {6865676,2,ch100st};

/* char: 0x65 */

static const SFG_StrokeVertex ch101st0[] =
{
 {1560379,2496607},
 {5305296,2496607},
 {5305296,3120758},
 {4993220,3744917},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch101st[] =
{
 {17,ch101st0}
};

static const SFG_StrokeChar ch101 = {6865676,1,ch101st};

/* char: 0x66 */

static const SFG_StrokeVertex ch102st0[] =
{
 {4681144,6553600},
 {4056993,6553600},
 {3432841,6241524},
 {3120765,5305296},
 {3120765,0}
};

static const SFG_StrokeVertex ch102st1[] =
{
 {2184537,4369069},
 {4369069,4369069}
};

static const SFG_StrokeStrip ch102st[] =
{
 {5,ch102st0},
 {2,ch102st1}
};

static const SFG_StrokeChar ch102 = {6865676,2,ch102st};

/* char: 0x67 */

static const SFG_StrokeVertex ch103st0[] =
{
 {5305296,4369069},
 {5305296,-624151},
 {4993220,-1560379},
 {4681138,-1872455},
 {4056986,-2184531},
 {3120758,-2184531},
 {2496607,-1872455}
};

static const SFG_StrokeVertex ch103st1[] =
{
 {5305296,3432841},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch103st[] =
{
 {7,ch103st0},
 {14,ch103st1}
};

static const SFG_StrokeChar ch103 = {6865676,2,ch103st};

/* char: 0x68 */

static const SFG_StrokeVertex ch104st0[] =
{
 {1716420,6553600},
 {1716420,0}
};

static const SFG_StrokeVertex ch104st1[] =
{
 {1716420,3120758},
 {2652648,4056993},
 {3276800,4369069},
 {4213027,4369069},
 {4837179,4056993},
 {5149262,3120758},
 {5149262,0}
};

static const SFG_StrokeStrip ch104st[] =
{
 {2,ch104st0},
 {7,ch104st1}
};

static const SFG_StrokeChar ch104 = {6865676,2,ch104st};

/* char: 0x69 */

static const SFG_StrokeVertex ch105st0[] =
{
 {3120765,6553600},
 {3432841,6241524},
 {3744917,6553600},
 {3432841,6865676},
 {3120765,6553600}
};

static const SFG_StrokeVertex ch105st1[] =
{
 {3432841,4369069},
 {3432841,0}
};

static const SFG_StrokeStrip ch105st[] =
{
 {5,ch105st0},
 {2,ch105st1}
};

static const SFG_StrokeChar ch105 = {6865676,2,ch105st};

/* char: 0x6a */

static const SFG_StrokeVertex ch106st0[] =
{
 {3744917,6553600},
 {4056993,6241524},
 {4369069,6553600},
 {4056993,6865676},
 {3744917,6553600}
};

static const SFG_StrokeVertex ch106st1[] =
{
 {4056993,4369069},
 {4056993,-936227},
 {3744917,-1872455},
 {3120765,-2184531},
 {2496613,-2184531}
};

static const SFG_StrokeStrip ch106st[] =
{
 {5,ch106st0},
 {5,ch106st1}
};

static const SFG_StrokeChar ch106 = {6865676,2,ch106st};

/* char: 0x6b */

static const SFG_StrokeVertex ch107st0[] =
{
 {1716420,6553600},
 {1716420,0}
};

static const SFG_StrokeVertex ch107st1[] =
{
 {4837179,4369069},
 {1716420,1248303}
};

static const SFG_StrokeVertex ch107st2[] =
{
 {2964724,2496607},
 {5149262,0}
};

static const SFG_StrokeStrip ch107st[] =
{
 {2,ch107st0},
 {2,ch107st1},
 {2,ch107st2}
};

static const SFG_StrokeChar ch107 = {6865676,3,ch107st};

/* char: 0x6c */

static const SFG_StrokeVertex ch108st0[] =
{
 {3432841,6553600},
 {3432841,0}
};

static const SFG_StrokeStrip ch108st[] =
{
 {2,ch108st0}
};

static const SFG_StrokeChar ch108 = {6865676,1,ch108st};

/* char: 0x6d */

static const SFG_StrokeVertex ch109st0[] =
{
 {0,4369069},
 {0,0}
};

static const SFG_StrokeVertex ch109st1[] =
{
 {0,3120758},
 {936227,4056993},
 {1560379,4369069},
 {2496607,4369069},
 {3120758,4056993},
 {3432841,3120758},
 {3432841,0}
};

static const SFG_StrokeVertex ch109st2[] =
{
 {3432841,3120758},
 {4369069,4056993},
 {4993220,4369069},
 {5929448,4369069},
 {6553600,4056993},
 {6865676,3120758},
 {6865676,0}
};

static const SFG_StrokeStrip ch109st[] =
{
 {2,ch109st0},
 {7,ch109st1},
 {7,ch109st2}
};

static const SFG_StrokeChar ch109 = {6865676,3,ch109st};

/* char: 0x6e */

static const SFG_StrokeVertex ch110st0[] =
{
 {1716420,4369069},
 {1716420,0}
};

static const SFG_StrokeVertex ch110st1[] =
{
 {1716420,3120758},
 {2652648,4056993},
 {3276800,4369069},
 {4213027,4369069},
 {4837179,4056993},
 {5149262,3120758},
 {5149262,0}
};

static const SFG_StrokeStrip ch110st[] =
{
 {2,ch110st0},
 {7,ch110st1}
};

static const SFG_StrokeChar ch110 = {6865676,2,ch110st};

/* char: 0x6f */

static const SFG_StrokeVertex ch111st0[] =
{
 {2964724,4369069},
 {2340572,4056993},
 {1716420,3432841},
 {1404344,2496607},
 {1404344,1872455},
 {1716420,936227},
 {2340572,312075},
 {2964724,0},
 {3900951,0},
 {4525103,312075},
 {5149255,936227},
 {5461337,1872455},
 {5461337,2496607},
 {5149255,3432841},
 {4525103,4056993},
 {3900951,4369069},
 {2964724,4369069}
};

static const SFG_StrokeStrip ch111st[] =
{
 {17,ch111st0}
};

static const SFG_StrokeChar ch111 = {6865676,1,ch111st};

/* char: 0x70 */

static const SFG_StrokeVertex ch112st0[] =
{
 {1560379,4369069},
 {1560379,-2184531}
};

static const SFG_StrokeVertex ch112st1[] =
{
 {1560379,3432841},
 {2184531,4056993},
 {2808683,4369069},
 {3744910,4369069},
 {4369062,4056993},
 {4993220,3432841},
 {5305296,2496607},
 {5305296,1872455},
 {4993220,936227},
 {4369062,312075},
 {3744910,0},
 {2808683,0},
 {2184531,312075},
 {1560379,936227}
};

static const SFG_StrokeStrip ch112st[] =
{
 {2,ch112st0},
 {14,ch112st1}
};

static const SFG_StrokeChar ch112 = {6865676,2,ch112st};

/* char: 0x71 */

static const SFG_StrokeVertex ch113st0[] =
{
 {5305296,4369069},
 {5305296,-2184531}
};

static const SFG_StrokeVertex ch113st1[] =
{
 {5305296,3432841},
 {4681138,4056993},
 {4056986,4369069},
 {3120758,4369069},
 {2496607,4056993},
 {1872455,3432841},
 {1560379,2496607},
 {1560379,1872455},
 {1872455,936227},
 {2496607,312075},
 {3120758,0},
 {4056986,0},
 {4681138,312075},
 {5305296,936227}
};

static const SFG_StrokeStrip ch113st[] =
{
 {2,ch113st0},
 {14,ch113st1}
};

static const SFG_StrokeChar ch113 = {6865676,2,ch113st};

/* char: 0x72 */

static const SFG_StrokeVertex ch114st0[] =
{
 {2184537,4369069},
 {2184537,0}
};

static const SFG_StrokeVertex ch114st1[] =
{
 {2184537,2496607},
 {2496613,3432841},
 {3120765,4056993},
 {3744917,4369069},
 {4681144,4369069}
};

static const SFG_StrokeStrip ch114st[] =
{
 {2,ch114st0},
 {5,ch114st1}
};

static const SFG_StrokeChar ch114 = {6865676,2,ch114st};

/* char: 0x73 */

static const SFG_StrokeVertex ch115st0[] =
{
 {5149262,3432841},
 {4837179,4056993},
 {3900951,4369069},
 {2964724,4369069},
 {2028496,4056993},
 {1716420,3432841},
 {2028496,2808683},
 {2652648,2496607},
 {4213027,2184531},
 {4837179,1872455},
 {5149262,1248303},
 {5149262,936227},
 {4837179,312075},
 {3900951,0},
 {2964724,0},
 {2028496,312075},
 {1716420,936227}
};

static const SFG_StrokeStrip ch115st[] =
{
 {17,ch115st0}
};

static const SFG_StrokeChar ch115 = {6865676,1,ch115st};

/* char: 0x74 */

static const SFG_StrokeVertex ch116st0[] =
{
 {3120765,6553600},
 {3120765,1248303},
 {3432841,312075},
 {4056993,0},
 {4681144,0}
};

static const SFG_StrokeVertex ch116st1[] =
{
 {2184537,4369069},
 {4369069,4369069}
};

static const SFG_StrokeStrip ch116st[] =
{
 {5,ch116st0},
 {2,ch116st1}
};

static const SFG_StrokeChar ch116 = {6865676,2,ch116st};

/* char: 0x75 */

static const SFG_StrokeVertex ch117st0[] =
{
 {1716420,4369069},
 {1716420,1248303},
 {2028496,312075},
 {2652648,0},
 {3588876,0},
 {4213027,312075},
 {5149262,1248303}
};

static const SFG_StrokeVertex ch117st1[] =
{
 {5149262,4369069},
 {5149262,0}
};

static const SFG_StrokeStrip ch117st[] =
{
 {7,ch117st0},
 {2,ch117st1}
};

static const SFG_StrokeChar ch117 = {6865676,2,ch117st};

/* char: 0x76 */

static const SFG_StrokeVertex ch118st0[] =
{
 {1560379,4369069},
 {3432834,0}
};

static const SFG_StrokeVertex ch118st1[] =
{
 {5305296,4369069},
 {3432834,0}
};

static const SFG_StrokeStrip ch118st[] =
{
 {2,ch118st0},
 {2,ch118st1}
};

static const SFG_StrokeChar ch118 = {6865676,2,ch118st};

/* char: 0x77 */

static const SFG_StrokeVertex ch119st0[] =
{
 {936227,4369069},
 {2184531,0}
};

static const SFG_StrokeVertex ch119st1[] =
{
 {3432834,4369069},
 {2184531,0}
};

static const SFG_StrokeVertex ch119st2[] =
{
 {3432834,4369069},
 {4681144,0}
};

static const SFG_StrokeVertex ch119st3[] =
{
 {5929448,4369069},
 {4681144,0}
};

static const SFG_StrokeStrip ch119st[] =
{
 {2,ch119st0},
 {2,ch119st1},
 {2,ch119st2},
 {2,ch119st3}
};

static const SFG_StrokeChar ch119 = {6865676,4,ch119st};

/* char: 0x78 */

static const SFG_StrokeVertex ch120st0[] =
{
 {1716420,4369069},
 {5149262,0}
};

static const SFG_StrokeVertex ch120st1[] =
{
 {5149262,4369069},
 {1716420,0}
};

static const SFG_StrokeStrip ch120st[] =
{
 {2,ch120st0},
 {2,ch120st1}
};

static const SFG_StrokeChar ch120 = {6865676,2,ch120st};

/* char: 0x79 */

static const SFG_StrokeVertex ch121st0[] =
{
 {1716420,4369069},
 {3588876,0}
};

static const SFG_StrokeVertex ch121st1[] =
{
 {5461337,4369069},
 {3588876,0},
 {2964724,-1248303},
 {2340572,-1872455},
 {1716420,-2184531},
 {1404344,-2184531}
};

static const SFG_StrokeStrip ch121st[] =
{
 {2,ch121st0},
 {6,ch121st1}
};

static const SFG_StrokeChar ch121 = {6865676,2,ch121st};

/* char: 0x7a */

static const SFG_StrokeVertex ch122st0[] =
{
 {5149262,4369069},
 {1716420,0}
};

static const SFG_StrokeVertex ch122st1[] =
{
 {1716420,4369069},
 {5149262,4369069}
};

static const SFG_StrokeVertex ch122st2[] =
{
 {1716420,0},
 {5149262,0}
};

static const SFG_StrokeStrip ch122st[] =
{
 {2,ch122st0},
 {2,ch122st1},
 {2,ch122st2}
};

static const SFG_StrokeChar ch122 = {6865676,3,ch122st};

/* char: 0x7b */

static const SFG_StrokeVertex ch123st0[] =
{
 {4213027,7801903},
 {3588876,7489827},
 {3276800,7177752},
 {2964724,6553600},
 {2964724,5929448},
 {3276800,5305296},
 {3588876,4993220},
 {3900951,4369069},
 {3900951,3744917},
 {3276800,3120758}
};

static const SFG_StrokeVertex ch123st1[] =
{
 {3588876,7489827},
 {3276800,6865676},
 {3276800,6241524},
 {3588876,5617372},
 {3900951,5305296},
 {4213027,4681144},
 {4213027,4056993},
 {3900951,3432841},
 {2652648,2808683},
 {3900951,2184531},
 {4213027,1560379},
 {4213027,936227},
 {3900951,312075},
 {3588876,0},
 {3276800,-624151},
 {3276800,-1248303},
 {3588876,-1872455}
};

static const SFG_StrokeVertex ch123st2[] =
{
 {3276800,2496607},
 {3900951,1872455},
 {3900951,1248303},
 {3588876,624151},
 {3276800,312075},
 {2964724,-312075},
 {2964724,-936227},
 {3276800,-1560379},
 {3588876,-1872455},
 {4213027,-2184531}
};

static const SFG_StrokeStrip ch123st[] =
{
 {10,ch123st0},
 {17,ch123st1},
 {10,ch123st2}
};

static const SFG_StrokeChar ch123 = {6865676,3,ch123st};

/* char: 0x7c */

static const SFG_StrokeVertex ch124st0[] =
{
 {3432841,7801903},
 {3432841,-2184531}
};

static const SFG_StrokeStrip ch124st[] =
{
 {2,ch124st0}
};

static const SFG_StrokeChar ch124 = {6865676,1,ch124st};

/* char: 0x7d */

static const SFG_StrokeVertex ch125st0[] =
{
 {2652648,7801903},
 {3276800,7489827},
 {3588876,7177752},
 {3900951,6553600},
 {3900951,5929448},
 {3588876,5305296},
 {3276800,4993220},
 {2964724,4369069},
 {2964724,3744917},
 {3588876,3120758}
};

static const SFG_StrokeVertex ch125st1[] =
{
 {3276800,7489827},
 {3588876,6865676},
 {3588876,6241524},
 {3276800,5617372},
 {2964724,5305296},
 {2652648,4681144},
 {2652648,4056993},
 {2964724,3432841},
 {4213027,2808683},
 {2964724,2184531},
 {2652648,1560379},
 {2652648,936227},
 {2964724,312075},
 {3276800,0},
 {3588876,-624151},
 {3588876,-1248303},
 {3276800,-1872455}
};

static const SFG_StrokeVertex ch125st2[] =
{
 {3588876,2496607},
 {2964724,1872455},
 {2964724,1248303},
 {3276800,624151},
 {3588876,312075},
 {3900951,-312075},
 {3900951,-936227},
 {3588876,-1560379},
 {3276800,-1872455},
 {2652648,-2184531}
};

static const SFG_StrokeStrip ch125st[] =
{
 {10,ch125st0},
 {17,ch125st1},
 {10,ch125st2}
};

static const SFG_StrokeChar ch125 = {6865676,3,ch125st};

/* char: 0x7e */

static const SFG_StrokeVertex ch126st0[] =
{
 {624151,1872455},
 {624151,2496607},
 {936227,3432841},
 {1560379,3744917},
 {2184531,3744917},
 {2808683,3432841},
 {4056993,2496607},
 {4681144,2184531},
 {5305296,2184531},
 {5929448,2496607},
 {6241524,3120758}
};

static const SFG_StrokeVertex ch126st1[] =
{
 {624151,2496607},
 {936227,3120758},
 {1560379,3432841},
 {2184531,3432841},
 {2808683,3120758},
 {4056993,2184531},
 {4681144,1872455},
 {5305296,1872455},
 {5929448,2184531},
 {6241524,3120758},
 {6241524,3744917}
};

static const SFG_StrokeStrip ch126st[] =
{
 {11,ch126st0},
 {11,ch126st1}
};

static const SFG_StrokeChar ch126 = {6865676,2,ch126st};

/* char: 0x7f */

static const SFG_StrokeVertex ch127st0[] =
{
 {4681144,6553600},
 {2184531,-2184531}
};

static const SFG_StrokeVertex ch127st1[] =
{
 {3120758,4369069},
 {2184531,4056993},
 {1560379,3432841},
 {1248303,2496607},
 {1248303,1560379},
 {1560379,936227},
 {2184531,312075},
 {3120758,0},
 {3744910,0},
 {4681144,312075},
 {5305296,936227},
 {5617372,1872455},
 {5617372,2808683},
 {5305296,3432841},
 {4681144,4056993},
 {3744910,4369069},
 {3120758,4369069}
};

static const SFG_StrokeStrip ch127st[] =
{
 {2,ch127st0},
 {17,ch127st1}
};

static const SFG_StrokeChar ch127 = {6865676,2,ch127st};

static const SFG_StrokeChar *chars[] =
{
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 &ch32, &ch33, &ch34, &ch35, &ch36, &ch37, &ch38, &ch39,
 &ch40, &ch41, &ch42, &ch43, &ch44, &ch45, &ch46, &ch47,
 &ch48, &ch49, &ch50, &ch51, &ch52, &ch53, &ch54, &ch55,
 &ch56, &ch57, &ch58, &ch59, &ch60, &ch61, &ch62, &ch63,
 &ch64, &ch65, &ch66, &ch67, &ch68, &ch69, &ch70, &ch71,
 &ch72, &ch73, &ch74, &ch75, &ch76, &ch77, &ch78, &ch79,
 &ch80, &ch81, &ch82, &ch83, &ch84, &ch85, &ch86, &ch87,
 &ch88, &ch89, &ch90, &ch91, &ch92, &ch93, &ch94, &ch95,
 &ch96, &ch97, &ch98, &ch99, &ch100, &ch101, &ch102, &ch103,
 &ch104, &ch105, &ch106, &ch107, &ch108, &ch109, &ch110, &ch111,
 &ch112, &ch113, &ch114, &ch115, &ch116, &ch117, &ch118, &ch119,
 &ch120, &ch121, &ch122, &ch123, &ch124, &ch125, &ch126, &ch127
};

const SFG_StrokeFont fgStrokeMonoRoman = {"MonoRoman",128,9986434,chars};
